"use client";
import { useState } from "react";
import { Search, Plus } from "lucide-react";
import type { Activity, Journey, Selection, SourceRef } from "@/lib/momentum/types";
import { localDate } from "@/lib/gym/dates";
import { Action, Field, Picker, Sheet, SourceLabel, Empty } from "./MomentumUI";
export default function ActionChooser({ activities, journeys, title, busy, onSelect, onCreate, onClose, linksOnly = false }: { activities: Activity[]; journeys: Journey[]; title: string; busy: boolean; onSelect: (selection: Selection) => Promise<boolean>; onCreate: (id: string, content: string) => Promise<boolean>; onClose: () => void; linksOnly?: boolean }) {
  const [search, setSearch] = useState(""), [kind, setKind] = useState("All"), [why, setWhy] = useState(""), [minutes, setMinutes] = useState(""), [journey, setJourney] = useState(""), [newTitle, setNewTitle] = useState(""), [newId] = useState(() => crypto.randomUUID()), [validation, setValidation] = useState("");
  const selection = (source: SourceRef): Selection => ({ source, why, minutes: minutes ? Number(minutes) : null, journeyId: journey || null });
  const [today] = useState(() => localDate());
  const rank = (item: Activity) => item.status === "active" ? 0 : item.ref.kind === "task" && item.status !== "completed" ? 1 : item.date && item.date >= today && item.status !== "completed" ? 2 : item.status === "completed" ? 3 : 4;
  const items = activities.filter(item => (linksOnly || item.status !== "completed") && (kind === "All" || item.ref.kind === kind) && item.title.toLowerCase().includes(search.toLowerCase())).sort((a, b) => rank(a) - rank(b) || (rank(a) >= 3 ? (b.completedAt ?? b.date ?? "").localeCompare(a.completedAt ?? a.date ?? "") : (a.date ?? "").localeCompare(b.date ?? "")));
  return <Sheet open title={title} description={linksOnly ? "Link a canonical source. Completion stays in its original tool." : "Select an existing action. Choosing it does not change its schedule or completion."} onClose={onClose} full><div className="grid gap-3 sm:grid-cols-2"><Field label="Search actions" value={search} onChange={event => setSearch(event.target.value)} placeholder="Task, workout or event" /><Picker label="Source" value={kind} options={["All", "task", "workout", "event"]} onChange={setKind} /></div>
    {!linksOnly && <div className="grid gap-3 sm:grid-cols-3"><Field label="Why it matters (optional)" value={why} maxLength={3000} onChange={event => setWhy(event.target.value)} /><Field label="Time estimate in minutes (optional)" type="number" min={1} max={240} value={minutes} onChange={event => setMinutes(event.target.value)} /><div className="grid gap-2 text-sm"><label htmlFor="momentum-journey-link">Journey (optional)</label><select id="momentum-journey-link" className="gym-input min-h-12 rounded-2xl border bg-background px-3" value={journey} onChange={event => setJourney(event.target.value)}><option value="">No journey</option>{journeys.filter(item => item.status === "active").map(item => <option key={item.id} value={item.id}>{item.title}</option>)}</select></div></div>}
    <div className="space-y-2">{items.slice(0, 100).map(activity => <button type="button" disabled={busy} key={activity.key} className="momentum-source-choice flex min-h-16 w-full items-center justify-between gap-3 rounded-2xl border p-4 text-left disabled:opacity-50" onClick={async () => { if (await onSelect(selection(activity.ref))) onClose(); }}><span className="min-w-0"><span className="mb-2 block break-words font-medium">{activity.title}</span><SourceLabel activity={activity} /><span className="mt-1 block text-xs text-muted-foreground">{activity.date ?? "No scheduled date"} · {activity.status}</span></span><Search size={18} className="shrink-0 text-primary-plus" /></button>)}{!items.length && <Empty>No matching actions. Build or schedule workouts in Gym, plan events in Events, or add a simple To-Do action below.</Empty>}{items.length > 100 && <p className="text-xs text-muted-foreground">Showing the first 100 matches. Search to narrow the list.</p>}</div>
    <form className="space-y-3 border-t pt-4" onSubmit={async event => { event.preventDefault(); if (!newTitle.trim()) { setValidation("Name the action first."); return; } setValidation(""); if (await onCreate(newId, newTitle.trim()) && await onSelect(selection({ kind: "task", id: newId }))) onClose(); }}><Field label="New simple action (saved in To-Do)" required maxLength={3000} value={newTitle} onChange={event => setNewTitle(event.target.value)} /><Action type="submit" tone="orange" disabled={busy}><Plus size={16} />Create and select</Action>{validation && <p role="alert">{validation}</p>}</form>
  </Sheet>;
}
