"use client";
import { useEffect, useState } from "react";
import { Pause, Play, Timer } from "lucide-react";
import { focusDuration } from "@/lib/momentum/format";
import { elapsedFocus, sourceKey } from "@/lib/momentum/logic";
import type { Activity, Focus, SourceRef } from "@/lib/momentum/types";
import type { MomentumCommand } from "@/lib/momentum/validation";
import { Action, Field, Notes, Panel, SourceLink, Empty } from "./MomentumUI";
export function FocusStarter({ source, busy, onSave }: { source: SourceRef | null; busy: boolean; onSave: (command: MomentumCommand) => Promise<boolean> }) {
  const [minutes, setMinutes] = useState("10");
  return <Panel label="Start a focus session" className="space-y-4"><div className="flex items-center gap-2"><Timer size={18} className="text-primary-plus" /><h3 className="font-semibold">A little room to focus</h3></div><p className="text-sm text-muted-foreground">Work, reading or learning. Convenience durations; the timer leaves your task open.</p><div className="flex flex-wrap gap-2">{[10, 25, 45].map(value => <Action key={value} tone={Number(minutes) === value ? "blue" : "neutral"} aria-pressed={Number(minutes) === value} onClick={() => setMinutes(String(value))}>{value} min</Action>)}</div><Field label="Custom focus minutes" value={minutes} type="number" min={1} max={240} onChange={event => setMinutes(event.target.value)} /><Action tone="orange" disabled={busy || !Number.isInteger(Number(minutes)) || Number(minutes) < 1 || Number(minutes) > 240} onClick={() => void onSave({ type: "focus-start", id: crypto.randomUUID(), source, minutes: Number(minutes) })}><Play size={16} />Start focus session</Action></Panel>;
}
export default function FocusPanel({ focus, activities, busy, onSave, onComplete }: { focus: Focus; activities: Activity[]; busy: boolean; onSave: (command: MomentumCommand) => Promise<boolean>; onComplete: (id: string) => Promise<boolean> }) {
  const [now, setNow] = useState(() => Date.now()), [corrected, setCorrected] = useState(""), [notes, setNotes] = useState(focus.notes), [discard, setDiscard] = useState(false);
  useEffect(() => { const timer = setInterval(() => setNow(Date.now()), 1000); return () => clearInterval(timer); }, []);
  const elapsed = elapsedFocus(focus, now), remaining = Math.max(0, focus.plannedSeconds - elapsed), ready = remaining === 0 || focus.status === "awaiting" || focus.status === "saved", activity = focus.source ? activities.find(item => item.key === sourceKey(focus.source!)) : null;
  const control = (action: "pause" | "resume" | "finish" | "discard" | "extend") => onSave({ type: "focus-control", id: focus.id, action, ...(action === "extend" ? { minutes: 10 } : {}) });
  return <Panel label="Current focus session" className="space-y-4 momentum-accent-orange"><div className="flex items-center gap-2"><Timer size={19} /><h3 className="font-semibold">{focus.status === "saved" ? "Saved focus session" : ready ? "Ready to review" : focus.status === "paused" ? "Focus paused" : "Focus in progress"}</h3></div>{activity ? <div className="space-y-2"><p className="break-words font-medium">{activity.title}</p><SourceLink activity={activity} /></div> : <p className="text-sm text-muted-foreground">{focus.source ? "The linked action was removed; your logged focus remains." : "Independent work, reading or learning session"}</p>}
    <p className="text-3xl font-semibold tabular-nums" aria-label="Remaining time">{focus.status === "saved" ? `${focusDuration(focus.confirmedSeconds ?? 0)} logged` : `${Math.floor(remaining / 60)}:${String(remaining % 60).padStart(2, "0")}`}</p><p className="text-xs text-muted-foreground">Logged focus time is your record, not proof of attention. Recorded intervals are capped at the planned end.</p>
    {!ready && <div className="flex flex-wrap gap-2"><Action disabled={busy} onClick={() => void control(focus.status === "paused" ? "resume" : "pause")}>{focus.status === "paused" ? <Play size={16} /> : <Pause size={16} />}{focus.status === "paused" ? "Resume" : "Pause"}</Action><Action disabled={busy} onClick={() => void control("finish")}>Finish early</Action></div>}
    {(ready || focus.status === "paused") && <div className="space-y-3"><Field label="Confirm or correct logged seconds" type="number" min={0} max={elapsed} step={1} value={corrected || String(focus.confirmedSeconds ?? elapsed)} onChange={event => setCorrected(event.target.value)} /><Notes label="Focus note (optional)" value={notes} onChange={event => setNotes(event.target.value)} maxLength={3000} /><div className="flex flex-wrap gap-2"><Action disabled={busy} tone="orange" onClick={() => void onSave({ type: "focus-save", id: focus.id, seconds: Number(corrected || String(focus.confirmedSeconds ?? elapsed)), notes })}>Save session</Action>{focus.status !== "saved" && <Action disabled={busy} onClick={() => void control("extend")}>Extend by 10 minutes</Action>}</div></div>}
    {activity?.ref.kind === "task" && activity.status !== "completed" && <Action disabled={busy} onClick={() => void onComplete(activity.ref.id)}>Mark task completed</Action>}
    {focus.status !== "saved" && (discard ? <div className="space-y-2"><Empty>Discard this timer? It will not appear in logged focus totals. The linked task stays unchanged.</Empty><Action disabled={busy} onClick={() => void control("discard")}>Confirm discard</Action><Action onClick={() => setDiscard(false)}>Keep session</Action></div> : <Action disabled={busy} onClick={() => setDiscard(true)}>Discard timer</Action>)}
  </Panel>;
}
