"use client";
import { useAccountPreferences } from "@/app/components/shared/account/AccountPreferencesProvider";
import { quietNow } from "@/lib/account/preferences";
import { createContext, useContext, useState } from "react";
import Link from "next/link";
import { motion, useReducedMotion } from "framer-motion";
import { ArrowDown, ArrowUp, Eye, EyeOff, Pin, Plus, Settings2, Trash2 } from "lucide-react";
import { currencies, type MomentumBundle, type MomentumData } from "@/lib/momentum/types";
import { formatMoney, moneyInput, parseMoney, sourceKey } from "@/lib/momentum/logic";
import { goalWindow, reminderDue, ruleText, trackerFor, versionFor } from "@/lib/momentum/goals/evaluate";
import type { GoalEvaluation, GoalMetric, GoalRecord, GoalReminder, GoalRule, GoalScope, TrackedGoal } from "@/lib/momentum/goals/types";
import { ruleSchema } from "@/lib/momentum/goals/validation";
import type { MomentumCommand } from "@/lib/momentum/validation";
import { dateInZone, weekStart } from "@/lib/gym/dates";
import FinanceSelect from "../finance/FinanceSelect";
import { Action, Confirm, Empty, Field, Notes, Panel, Picker, Sheet } from "./MomentumUI";

const SaveContext = createContext<{ error: string; retry: () => void; busy: boolean }>({ error: "", retry: () => {}, busy: false });
function SaveError() { const { error, retry, busy } = useContext(SaveContext); return error ? <div role="alert" className="space-y-2 rounded-2xl border p-3 text-sm"><p>{error}</p><Action disabled={busy} onClick={retry}>Retry save</Action><p className="text-xs text-muted-foreground">Correct a rejected rule and submit again, or retry the original save after a connection failure.</p></div> : null; }
const names: Record<GoalMetric, string> = { balance: "Keep a minimum balance", savings: "Put money aside", sessions: "Complete workouts", "training-days": "Different training days", events: "Attend activities", visits: "Confirmed visits", minutes: "Spend time on an activity", investment: "Monthly account contributions" };
const moneyMetric = (metric: GoalMetric) => ["balance", "savings", "investment"].includes(metric);
const amount = (evaluation: GoalEvaluation, value: number | null, hidden: boolean) => value === null ? "Unknown" : hidden && moneyMetric(evaluation.rule.metric) ? "••••" : evaluation.rule.currency ? formatMoney(value, evaluation.rule.currency) : `${Number(value.toFixed(2))} ${evaluation.rule.metric === "minutes" ? "min" : evaluation.rule.metric === "training-days" ? "days" : evaluation.rule.metric === "visits" ? "visits" : evaluation.rule.metric === "events" ? "activities" : "sessions"}`;
const privateRule = (evaluation: GoalEvaluation, hidden: boolean) => hidden && evaluation.rule.currency ? evaluation.ruleText.replace(formatMoney(evaluation.rule.target, evaluation.rule.currency), "the hidden minimum") : evaluation.ruleText;
const reminderDefault = (): GoalReminder => ({ enabled: false, days: [1], time: "18:00", leadDays: null });
function ReminderSettings({ value, onChange }: { value: GoalReminder; onChange: (value: GoalReminder) => void }) {
  return <fieldset className="space-y-3 rounded-2xl border p-4"><legend className="px-2 text-sm font-medium">Optional in-app reminder</legend><label className="flex min-h-11 items-center gap-3"><input type="checkbox" className="size-5" checked={value.enabled} onChange={e => onChange({ ...value, enabled: e.target.checked })} />Show when I open Momentum</label>{value.enabled && <><div className="flex flex-wrap gap-2">{["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"].map((day, index) => <Action key={day} aria-pressed={value.days.includes(index)} tone={value.days.includes(index) ? "blue" : "neutral"} onClick={() => onChange({ ...value, days: value.days.includes(index) ? value.days.filter(x => x !== index) : [...value.days, index] })}>{day}</Action>)}</div><Field label="Remind after local time" type="time" value={value.time} onInput={e => onChange({ ...value, time: e.currentTarget.value })} onChange={e => onChange({ ...value, time: e.target.value })} /><Field label="Or lead days before period end (optional)" type="number" min={0} max={30} value={value.leadDays ?? ""} onChange={e => onChange({ ...value, leadDays: e.target.value === "" ? null : Number(e.target.value) })} /></>}<p className="text-xs text-muted-foreground">Optional email delivery is controlled in Account & Settings; no duplicate task is created. Met targets suppress this period&apos;s reminder. Snooze/dismiss does not change actual progress.</p></fieldset>;
}
function ScopeEditor({ kind, currency, busy, onSave, onClose, onCreated }: { kind: GoalScope["kind"]; currency: GoalScope["currency"]; busy: boolean; onSave: (command: MomentumCommand) => Promise<boolean>; onClose: () => void; onCreated: (id: string) => void }) {
  const [id] = useState(() => crypto.randomUUID()), [name, setName] = useState("");
  return <Sheet open title={`Name your ${kind === "activity" ? "activity" : kind === "investment" ? "investment account" : "cash account/scope"}`} description="Manual records only. The name identifies what is included; no bank, broker, or location connection is created." onClose={onClose}><form className="space-y-4" onSubmit={async e => { e.preventDefault(); if (await onSave({ type: "goal-scope", id, name, kind, currency })) { onCreated(id); onClose(); } }}><Field label="Scope name" value={name} required maxLength={100} onChange={e => setName(e.target.value)} /><p className="text-sm text-muted-foreground">{currency ?? "Confirmed visits and duration intervals"}. Share this source across goal cards to avoid duplicated logs. {kind === "cash" && "Treat transfers within this scope as internal; only transfers across its boundary change its balance."}</p><SaveError /><Action type="submit" tone="orange" disabled={busy}>Create record scope</Action></form></Sheet>;
}
function GoalEditor({ initial, bundle, busy, onSave, onClose, onMoney }: { initial: TrackedGoal | null; bundle: MomentumBundle; busy: boolean; onSave: (command: MomentumCommand) => Promise<boolean>; onClose: () => void; onMoney: () => void }) {
  const {settings}=useAccountPreferences();
  const data = bundle.record.data, tracker = trackerFor(data), original = initial ? versionFor(initial, bundle.today).rule : null;
  const [id] = useState(initial?.id ?? crypto.randomUUID()), [name, setName] = useState(initial?.name ?? ""), [target, setTarget] = useState(original ? original.currency ? moneyInput(original.target, original.currency) : String(original.target) : ""), [rule, setRule] = useState<GoalRule>(original ?? { metric: "sessions", target: 1, currency: null, period: "weekly", start: bundle.today, end: null, timezone: bundle.timezone, scopeId: null, sources: [], journeyId: null, throughout: false, freshnessDays: 7, weekStartsOn:settings.preferences.weekStart }), [reminder, setReminder] = useState(initial?.reminder ?? reminderDefault()), [includePeriod, setIncludePeriod] = useState(false), [apply, setApply] = useState<"current" | "next">("current"), [preview, setPreview] = useState(false), [error, setError] = useState(""), [scopeOpen, setScopeOpen] = useState(false);
  const patch = (change: Partial<GoalRule>) => { setRule({ ...rule, ...change }); setPreview(false); };
  const kind = rule.metric === "balance" ? "cash" : rule.metric === "investment" ? "investment" : "activity";
  const scopes = rule.metric === "savings" ? data.savings.filter(x => x.currency === rule.currency).map(x => ({ id: x.id, name: x.name })) : tracker.scopes.filter(x => x.kind === kind && x.currency === rule.currency);
  const parsedRule = () => ({ ...rule, target: rule.currency ? parseMoney(target, rule.currency) : Number(target), start: initial ? rule.start : includePeriod && rule.period === "weekly" ? weekStart(bundle.today,rule.weekStartsOn??"monday") : includePeriod && rule.period === "monthly" ? `${bundle.today.slice(0, 7)}-01` : rule.start });
  return <><Sheet open full title={initial ? "Edit goal rule" : "Create a measured goal"} description="Choose what counts. Source records stay in their existing tools; a goal card does not create a task or commitment automatically." onClose={onClose}><form className="space-y-5" onSubmit={async e => { e.preventDefault(); setError(""); try { const parsed = ruleSchema.safeParse(parsedRule()); if (!parsed.success) throw new Error(parsed.error.issues[0].message); const value = parsed.data; if (!preview) { setPreview(true); return; } if (await onSave({ type: "goal-save", id, name, rule: value, apply, reminder })) onClose(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Check the target"); } }}>
    {!initial && <div className="flex flex-wrap gap-2">{(["balance", "savings", "sessions", "minutes", "investment"] as GoalMetric[]).filter(x => data.preferences.money || !moneyMetric(x)).map(metric => <Action key={metric} tone={rule.metric === metric ? "blue" : "neutral"} onClick={() => { setTarget(""); patch({ metric, currency: metric === "investment" ? "USD" : moneyMetric(metric) ? settings.preferences.financeDefaultCurrency : null, period: metric === "balance" ? "ongoing" : metric === "investment" || metric === "savings" ? "monthly" : "weekly", scopeId: null, sources: [], throughout: false }); }}>{names[metric]}</Action>)}</div>}
    <Field label="Goal name" required maxLength={200} value={name} onChange={e => { setName(e.target.value); setPreview(false); }} />
    <div className="grid gap-4 sm:grid-cols-2"><Picker label="Counting rule" value={names[rule.metric]} options={Object.entries(names).filter(([metric]) => data.preferences.money || !moneyMetric(metric as GoalMetric)).map(([, label]) => label)} onChange={label => { const metric = (Object.entries(names).find(([, value]) => value === label)![0]) as GoalMetric; setTarget(""); patch({ metric, currency: metric === "investment" ? "USD" : moneyMetric(metric) ? settings.preferences.financeDefaultCurrency : null, scopeId: null, sources: [], throughout: false, period: initial ? rule.period : metric === "balance" ? "ongoing" : rule.period }); }} />{rule.currency && <Picker label="Currency" value={rule.currency} options={rule.metric==="investment"?["USD"]:currencies} onChange={currency => patch({ currency: currency as GoalRule["currency"], scopeId: null })} />}<Field label={`Target ${rule.currency ? `(${rule.currency})` : rule.metric === "minutes" ? "(minutes)" : "(count)"}`} inputMode={rule.currency ? "decimal" : "numeric"} required value={target} onChange={e => { setTarget(e.target.value); setPreview(false); }} /><Picker label="Period" disabled={!!initial} value={rule.period} options={rule.metric === "balance" ? ["ongoing", "monthly", "range"] : ["weekly", "monthly", "ongoing", "range"]} onChange={period => patch({ period: period as GoalRule["period"] })} /><Field label="Start date" type="date" required disabled={!!initial || includePeriod && ["weekly", "monthly"].includes(rule.period)} value={includePeriod && rule.period === "weekly" ? weekStart(bundle.today,rule.weekStartsOn??"monday") : includePeriod && rule.period === "monthly" ? `${bundle.today.slice(0, 7)}-01` : rule.start} onChange={e => patch({ start: e.target.value })} /><Field label={rule.period === "range" ? "End date" : "End date (optional)"} type="date" required={rule.period === "range"} min={rule.start} value={rule.end ?? ""} onChange={e => patch({ end: e.target.value || null })} /></div>
    {!initial && ["weekly", "monthly"].includes(rule.period) && <label className="flex min-h-11 items-center gap-3"><input type="checkbox" className="size-5" checked={includePeriod} onChange={e => { setIncludePeriod(e.target.checked); setPreview(false); }} />Include eligible records from this entire current calendar period. Otherwise starts on the chosen start date. Target is never prorated.</label>}
    {["balance", "savings", "investment", "visits", "minutes"].includes(rule.metric) && <div className="space-y-3"><FinanceSelect icon={Settings2} title="Record sources" label={rule.metric === "savings" ? "Savings allocation" : "Named source scope"} value={rule.scopeId ?? ""} options={[{value:"",label:"Choose a scope"}, ...scopes.map(x => ({value:x.id,label:x.name}))]} onValueChange={scopeId => patch({ scopeId: scopeId || null })} />{rule.metric === "savings" ? <Action onClick={onMoney}>Manage savings allocations</Action> : <Action onClick={() => setScopeOpen(true)}>Add named {kind} scope</Action>}<p className="text-xs text-muted-foreground">{rule.metric === "savings" ? "Uses the existing savings journal, excluding its opening balance." : "Manual records in this source are reusable; record a movement/visit once. No external account connection."}</p></div>}
    {["minutes", "events"].includes(rule.metric) && <div className="space-y-2"><p className="text-sm font-medium">Choose which source actions count</p><div className="max-h-48 overflow-y-auto rounded-2xl border p-3">{bundle.activities.filter(x => rule.metric === "minutes" || x.ref.kind === "event").map(activity => <label key={activity.key} className="flex min-h-11 items-center gap-3 text-sm"><input type="checkbox" className="size-5" checked={rule.sources.some(x => sourceKey(x) === activity.key)} onChange={e => patch({ sources: e.target.checked ? [...rule.sources, activity.ref] : rule.sources.filter(x => sourceKey(x) !== activity.key) })} />{activity.title} · {activity.ref.kind}{activity.date ? ` · ${activity.date}` : ""}</label>)}</div>{rule.sources.filter(ref => !bundle.activities.some(activity => activity.key === sourceKey(ref))).map(ref => <Action key={sourceKey(ref)} onClick={() => patch({sources:rule.sources.filter(value => sourceKey(value) !== sourceKey(ref))})}>Remove unavailable source · {sourceKey(ref)}</Action>)}<p className="text-xs text-muted-foreground">{rule.metric === "events" ? "No selection counts all confirmed manual Events. Training links count through Gym only." : "Only selected actions or the linked journey’s action references count. A manual activity scope can supply confirmed intervals from elsewhere."}</p></div>}
    <FinanceSelect icon={Settings2} title="Journeys" label="Optional linked journey" value={rule.journeyId ?? ""} options={[{value:"",label:"No journey"}, ...data.journeys.map(x => ({value:x.id,label:x.title}))]} onValueChange={journeyId => patch({ journeyId: journeyId || null })} />
    {rule.metric === "balance" && <div className="space-y-3"><label className="flex min-h-11 items-center gap-3"><input type="checkbox" className="size-5" checked={rule.throughout} onChange={e => patch({ throughout: e.target.checked })} />Maintain throughout the period; require recorded coverage, not only the final snapshot</label><Field label="Needs update after this many days without a dated movement" type="number" min={1} max={365} value={rule.freshnessDays} onChange={e => patch({ freshnessDays: Number(e.target.value) })} /></div>}
    <ReminderSettings value={reminder} onChange={value => { setReminder(value); setPreview(false); }} />
    {initial && <Picker label="Apply target/filter edit" value={apply === "current" ? "Revise current period" : "From next period"} options={["Revise current period", ...(["weekly", "monthly"].includes(rule.period) ? ["From next period"] : [])]} onChange={value => { setApply(value === "From next period" ? "next" : "current"); setPreview(false); }} />}
    {preview && <Panel className="space-y-3"><h3 className="font-semibold">Rule preview</h3><p className="text-sm">{ruleText(parsedRule(), data)}</p><p className="text-sm">Target: {rule.currency ? formatMoney(parsedRule().target, rule.currency) : `${target} ${rule.metric === "minutes" ? "minutes" : "count"}`} · {goalWindow(parsedRule(), bundle.today).label} · {rule.timezone}</p><p className="text-xs text-muted-foreground">{initial ? `Creates rule revision ${initial.versions.length + 1}, ${apply === "next" ? "effective next period" : "recalculating this period"}. Earlier period definitions and your written reviews remain unchanged.` : "No example progress or financial records will be created."}</p></Panel>}
    {error && <p role="alert">{error}</p>}<SaveError /><Action type="submit" disabled={busy} tone="orange">{busy ? "Saving…" : preview ? "Confirm goal rule" : "Preview rule"}</Action>
  </form></Sheet>{scopeOpen && <ScopeEditor kind={kind} currency={rule.currency} busy={busy} onSave={onSave} onClose={() => setScopeOpen(false)} onCreated={scopeId => patch({ scopeId })} />}</>;
}

function localInput(instant: string, zone: string) { const parts = new Intl.DateTimeFormat("en-CA", { timeZone: zone, year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", hourCycle: "h23" }).formatToParts(new Date(instant)); return `${["year", "month", "day"].map(k => parts.find(x => x.type === k)!.value).join("-")}T${["hour", "minute"].map(k => parts.find(x => x.type === k)!.value).join(":")}`; }
function parseLocalInput(input: string, zone: string) { let instant = Date.parse(`${input}:00Z`); const target = instant; for (let i = 0; i < 4; i++) { const wall = Date.parse(`${localInput(new Date(instant).toISOString(), zone)}:00Z`); instant += target - wall; } if (localInput(new Date(instant).toISOString(), zone) !== input) throw new Error("Choose a valid local time outside the daylight-saving clock gap"); return new Date(instant).toISOString(); }
function RecordEditor({ scope, evaluation, data, initial, busy, onSave, onClose }: { scope: GoalScope; evaluation: GoalEvaluation; data: MomentumData; initial: GoalRecord | null; busy: boolean; onSave: (command: MomentumCommand) => Promise<boolean>; onClose: () => void }) {
  const [id] = useState(initial?.id ?? crypto.randomUUID()), [kind, setKind] = useState<GoalRecord["kind"]>(initial?.kind ?? (scope.kind === "cash" ? "snapshot" : scope.kind === "investment" ? "contribution" : evaluation.rule.metric === "visits" ? "visit" : "duration")), [reference, setReference] = useState(initial?.reference ?? ""), [value, setValue] = useState(initial ? scope.currency ? moneyInput(initial.value, scope.currency) : initial.kind === "duration" ? String(initial.value / 60) : "1" : ""), [time, setTime] = useState(() => localInput(initial?.occurredAt ?? new Date().toISOString(), evaluation.rule.timezone)), [note, setNote] = useState(initial?.note ?? ""), [linked, setLinked] = useState(initial?.linkedFocusId ?? ""), [coverage, setCoverage] = useState(initial?.confirmedThrough ?? ""), [error, setError] = useState("");
  const options = scope.kind === "cash" ? ["snapshot", "cash-in", "cash-out"] : scope.kind === "investment" ? ["contribution", "withdrawal"] : ["duration", "visit"];
  return <Sheet open title={initial ? "Correct a manual record" : "Record an actual update"} description={`Manually recorded · ${scope.name}. This never executes a payment, transfer or investment.`} onClose={onClose}><form className="space-y-4" onSubmit={async e => { e.preventDefault(); setError(""); try { const occurredAt = parseLocalInput(time, evaluation.rule.timezone), numeric = scope.currency ? kind === "snapshot" && value.startsWith("-") ? -parseMoney(value.slice(1), scope.currency) : parseMoney(value, scope.currency) : kind === "visit" ? 1 : Math.round(Number(value) * 60); if (!Number.isFinite(numeric)) throw new Error("Enter a valid amount or duration"); if (await onSave({ type: "goal-record", value: { id, scopeId: scope.id, kind, reference, date: dateInZone(new Date(occurredAt), evaluation.rule.timezone), occurredAt, value: numeric, note, linkedFocusId: kind === "duration" ? linked || null : null, confirmedThrough: kind === "snapshot" ? coverage || null : null } })) onClose(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Check the record"); } }}>
    <Picker label="Record type" value={kind} options={options} onChange={value => setKind(value as GoalRecord["kind"])} /><Field label="Unique actual record / visit group reference" required maxLength={100} value={reference} onChange={e => setReference(e.target.value)} /><Field label={`Occurred at (${evaluation.rule.timezone})`} type="datetime-local" required value={time} onInput={e => setTime(e.currentTarget.value)} onChange={e => setTime(e.target.value)} />{kind !== "visit" && <Field label={scope.currency ? `Amount (${scope.currency})${kind === "snapshot" ? " — negative balances allowed" : ""}` : "Actual minutes (not planned duration)"} inputMode="decimal" required value={value} onChange={e => setValue(e.target.value)} />}
    {kind === "snapshot" && <><p className="text-xs text-muted-foreground">An authoritative snapshot replaces earlier included movements. Enter later settled movements only; do not add investments or credit limits. Confirm statement coverage below only if all movements were checked.</p><Field label="All settled records checked through date (optional)" type="date" value={coverage} onChange={e => setCoverage(e.target.value)} /></>}
    {kind === "duration" && <Picker label="Same activity as an existing timer? (manual copy will not add time)" value={linked || "Separate recorded interval"} options={["Separate recorded interval", ...data.focus.filter(x => x.status === "saved").map(x => x.id)]} onChange={value => setLinked(value === "Separate recorded interval" ? "" : value)} />}
    {scope.kind === "investment" && <p className="text-xs text-muted-foreground">Confirmed external cash only. Do not record opening market value, dividends, gains or internal buys/sells as contributions. Use the same source record once rather than duplicating a bank transfer and broker deposit.</p>}
    <Notes label="Record note (optional)" value={note} maxLength={3000} onChange={e => setNote(e.target.value)} />{error && <p role="alert">{error}</p>}<SaveError /><Action type="submit" tone="orange" disabled={busy}>Save actual record</Action>
  </form></Sheet>;
}
function GoalDetails({ goal, evaluation, bundle, busy, onSave, onClose, onEdit, onMoney, onDelete, onRecord }: { goal: TrackedGoal; evaluation: GoalEvaluation; bundle: MomentumBundle; busy: boolean; onSave: (command: MomentumCommand) => Promise<boolean>; onClose: () => void; onEdit: () => void; onMoney: () => void; onDelete: () => void; onRecord: (record: GoalRecord | null) => void }) {
  const tracker = trackerFor(bundle.record.data), scope = tracker.scopes.find(x => x.id === evaluation.rule.scopeId), hide = tracker.hideAmounts, financial = moneyMetric(evaluation.rule.metric), records = tracker.records.filter(x => x.scopeId === scope?.id).sort((a, b) => b.occurredAt.localeCompare(a.occurredAt)), history = tracker.history.filter(x => x.goalId === goal.id).sort((a, b) => b.start.localeCompare(a.start)), [remove, setRemove] = useState<GoalRecord | null>(null);
  return <><Sheet open full title={goal.name} description="Source-backed calculation, prior periods and settings. Corrections recalculate affected periods without rewriting your personal reflections." onClose={onClose}>
    <Panel className="space-y-3"><p className="font-medium">{evaluation.status}</p><p className="text-2xl font-semibold text-primary-plus">{amount(evaluation, evaluation.value, hide)} / {amount(evaluation, evaluation.rule.target, hide)}</p><p className="text-sm">{privateRule(evaluation, hide)}</p><p className="text-xs text-muted-foreground">{evaluation.period.label} · rule revision {evaluation.version} · {evaluation.source} · {evaluation.asOf ? `as of ${evaluation.asOf}` : "No dated source update"}</p>{evaluation.revised && <p className="text-sm text-primary-minus">Revised after a rule/source correction.</p>}{evaluation.limitations.map(text => <p key={text} className="text-xs text-muted-foreground">{text}</p>)}<div className="flex flex-wrap gap-2"><Action onClick={onEdit}><Settings2 size={16} />Rule and reminders</Action><Action disabled={busy} onClick={() => void onSave({ type: "goal-card", id: goal.id, lifecycle: goal.lifecycle === "paused" ? "active" : "paused" })}>{goal.lifecycle === "paused" ? "Resume goal" : "Pause goal"}</Action><Action disabled={busy} onClick={() => void onSave({ type: "goal-card", id: goal.id, lifecycle: goal.lifecycle === "archived" ? "active" : "archived" })}>{goal.lifecycle === "archived" ? "Restore goal" : "Archive goal"}</Action><Action disabled={busy} onClick={onDelete}><Trash2 size={16} />Delete goal definition</Action></div></Panel>
    <Panel className="space-y-3"><h3 className="font-semibold">Contributing records</h3>{!evaluation.contributions.length && <Empty>No eligible actual records in this window. Check the selected source and period; missing logs do not prove nothing happened.</Empty>}{evaluation.contributions.map(item => <div key={item.key} className="space-y-1 rounded-2xl border p-3"><p className="text-sm">{item.label}</p><p className="text-xs text-muted-foreground">{item.date} · {amount(evaluation, item.value, hide)} · {item.manual ? "Manually recorded" : "Canonical app record"}</p>{item.href && <Link className="inline-flex min-h-11 items-center text-sm text-primary-plus underline" href={item.href}>Open source</Link>}</div>)}{evaluation.rule.metric === "savings" ? <Action onClick={onMoney}>Record contribution in savings journal</Action> : scope ? <Action onClick={() => onRecord(null)}>Record an actual update</Action> : <p className="text-xs text-muted-foreground">Manage these actual records in {evaluation.rule.metric === "events" ? "Events" : evaluation.rule.metric === "minutes" ? "the focus tool" : "Gym"}.</p>}</Panel>
    {scope && <Panel className="space-y-3"><h3 className="font-semibold">Manual source records · {scope.name}</h3><p className="text-xs text-muted-foreground">These are shared by every goal using this scope. Editing/removing a record recalculates all affected goals.</p>{records.map(record => <div key={record.id} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border p-3"><p className="text-sm">{record.date} · {record.reference} · {record.kind} · {financial && hide ? "••••" : scope.currency ? formatMoney(record.value, scope.currency) : record.kind === "duration" ? `${record.value / 60} min` : "1 visit"}</p><div className="flex gap-2"><Action onClick={() => onRecord(record)}>Correct</Action><Action aria-label={`Remove record ${record.reference}`} onClick={() => setRemove(record)}><Trash2 size={16} /></Action></div></div>)}</Panel>}
    <Panel className="space-y-3"><h3 className="font-semibold">Period history</h3><p className="text-xs text-muted-foreground">Earlier targets retain their rule revision. A corrected source recalculates recorded results and is marked Revised. Excess and shortfall never carry forward.</p>{history.slice(0, 24).map(item => { const version = goal.versions.find(x => x.revision === item.version); return <div key={item.key} className="rounded-2xl border p-3 text-sm"><p>{item.start} – {item.end ?? "ongoing"} · {item.status}</p><p className="text-xs text-muted-foreground">{version?.rule.currency && hide ? "••••" : version?.rule.currency && item.value !== null ? formatMoney(item.value, version.rule.currency) : `${item.value ?? "Unknown"} recorded`} · revision {item.version}{item.revisedAt ? ` · Revised ${item.revisedAt}` : ""}</p></div>; })}</Panel>
  </Sheet>{remove && <Confirm title="Remove this actual record?" description="All goals sharing this source will recalculate, including earlier periods. Goal definitions, source tasks/workouts and personal reviews remain unchanged." onClose={() => setRemove(null)} onConfirm={async () => { if (!await onSave({ type: "goal-remove-record", id: remove.id })) throw new Error("Save failed — retry"); }} />}</>;
}
function GoalTrackerBody({ bundle, busy, onSave, onMoney }: { bundle: MomentumBundle; busy: boolean; onSave: (command: MomentumCommand) => Promise<boolean>; onMoney: () => void }) {
  const {settings}=useAccountPreferences();
  const tracker = trackerFor(bundle.record.data), reduced = useReducedMotion(), evaluations = bundle.goalEvaluations ?? [], [editor, setEditor] = useState<TrackedGoal | "new" | null>(null), [detail, setDetail] = useState<string | null>(null), [showHidden, setShowHidden] = useState(false), [deleting, setDeleting] = useState<TrackedGoal | null>(null), [record, setRecord] = useState<{ goalId: string; initial: GoalRecord | null } | null>(null), [sourcesOpen, setSourcesOpen] = useState(false);
  const financialAllowed = (goal: TrackedGoal) => bundle.record.data.preferences.money || !moneyMetric(versionFor(goal, bundle.today).rule.metric);
  const goals = tracker.goals.filter(x => financialAllowed(x) && (showHidden || !x.hidden && x.lifecycle !== "archived")).sort((a, b) => Number(b.pinned) - Number(a.pinned) || a.order - b.order);
  const selected = tracker.goals.find(x => x.id === detail), evaluation = evaluations.find(x => x.goalId === detail), recordingGoal = evaluations.find(x => x.goalId === record?.goalId), recordingScope = tracker.scopes.find(x => x.id === recordingGoal?.rule.scopeId);
  return <section id="goal-tracker" className="space-y-4 scroll-mt-8" aria-label="Goal Tracker"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-semibold">Goal Tracker</h2><p className="mt-1 text-sm text-muted-foreground">Your rule. Recorded progress. One useful next step.</p></div><Action tone="blue" onClick={() => setEditor("new")}><Plus size={16} />Add goal</Action></div>
    <div className="flex flex-wrap gap-2">{!!tracker.scopes.length && <Action onClick={() => setSourcesOpen(true)}>Manage manual sources</Action>}{!!tracker.goals.length && <Action aria-pressed={showHidden} onClick={() => setShowHidden(!showHidden)}>{showHidden ? "Hide saved / archived cards" : "Manage hidden / archived cards"}</Action>}{bundle.record.data.preferences.money && <Action disabled={busy} onClick={() => void onSave({ type: "goal-hide-amounts", value: !tracker.hideAmounts })}>{tracker.hideAmounts ? <Eye size={16} /> : <EyeOff size={16} />}{tracker.hideAmounts ? "Show money amounts" : "Hide money amounts"}</Action>}</div>
    {!goals.length && <Empty>No measured goals selected. Add a workout count, a chosen activity&apos;s time, or an optional money target. Your mission and journeys can still stand on their own.</Empty>}
    <div className="grid items-start gap-4 lg:grid-cols-2">{goals.map(goal => { const evaluation = evaluations.find(x => x.goalId === goal.id); if (!evaluation) return <Panel key={goal.id}><p>{goal.name}</p><p role="status">Refreshing source calculation…</p></Panel>; const reminder = settings.notifications.goalReminders&&!quietNow(settings.notifications,new Date(),settings.preferences.timezone)?reminderDue(goal, evaluation, tracker, new Date().toISOString()):null, ratio = evaluation.value === null ? 0 : Math.max(0, Math.min(1, evaluation.value / evaluation.rule.target));
      return <Panel key={goal.id} id={`goal-${goal.id}`} className={`scroll-mt-8 space-y-3 ${evaluation.met ? "momentum-accent-orange" : "momentum-accent-blue"}`}><button type="button" className="w-full rounded-xl text-left outline-none focus-visible:ring-2 focus-visible:ring-primary-plus" onClick={() => setDetail(goal.id)}><p className="flex items-center gap-2 text-xs text-muted-foreground">{goal.pinned && <Pin size={13} />} {evaluation.period.label} · {goal.lifecycle}</p><h3 className="mt-2 text-lg font-semibold">{goal.name}</h3><p className="mt-2 text-sm text-muted-foreground">{evaluation.ruleText}</p><p className="mt-3 text-xl font-semibold">{amount(evaluation, evaluation.value, tracker.hideAmounts)} <span className="text-sm font-normal text-muted-foreground">/ {amount(evaluation, evaluation.rule.target, tracker.hideAmounts)}</span></p></button>
      {evaluation.rule.metric !== "balance" && !(tracker.hideAmounts && moneyMetric(evaluation.rule.metric)) && <div role="progressbar" aria-label={`${goal.name} recorded progress`} aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.round(ratio * 100)} aria-valuetext={`${amount(evaluation, evaluation.value, tracker.hideAmounts)} of ${amount(evaluation, evaluation.rule.target, tracker.hideAmounts)}`} className="h-2 overflow-hidden rounded-full bg-muted"><motion.div className={`h-full rounded-full ${evaluation.met ? "bg-primary-minus" : "bg-primary-plus"}`} initial={false} animate={{ width: `${ratio * 100}%` }} transition={{ duration: reduced ? 0 : 0.2 }} /></div>}
      <p className="text-sm font-medium">{evaluation.status}</p><p className="text-sm text-muted-foreground">{evaluation.buffer !== null ? `${amount(evaluation, Math.abs(evaluation.buffer), tracker.hideAmounts)} ${evaluation.buffer >= 0 ? "above minimum in recorded balance" : "below minimum"}` : evaluation.remaining === null ? "Needs a dated source update" : `${amount(evaluation, evaluation.remaining, tracker.hideAmounts)} remaining`}</p><p className="text-xs text-muted-foreground">{evaluation.source} · {evaluation.asOf ? `as of ${evaluation.asOf.length === 10 ? `${evaluation.asOf} (recorded date)` : `${new Intl.DateTimeFormat(undefined, {timeZone:evaluation.rule.timezone,dateStyle:"medium",timeStyle:"short"}).format(new Date(evaluation.asOf))} (${evaluation.rule.timezone})`}` : "No dated records"}{evaluation.revised ? " · Revised" : ""}</p>
      {evaluation.rule.metric === "balance" && <p className="text-xs text-muted-foreground">Based on recorded balance. Coverage may have gaps; open Details before relying on this amount.</p>}{evaluation.next.href ? <Link href={evaluation.next.href} className="gym-button inline-flex min-h-11 items-center rounded-2xl border px-3 py-2 text-sm text-primary-minus">{evaluation.next.label}</Link> : <Action disabled={busy} tone="orange" onClick={() => { if (evaluation.rule.metric === "savings") onMoney(); else if (evaluation.rule.metric === "minutes" && evaluation.next.source) void onSave({ type: "focus-start", id: crypto.randomUUID(), source: evaluation.next.source, minutes: 25 }); else { setDetail(goal.id); } }}>{evaluation.next.label}</Action>}
      <div className="flex flex-wrap gap-2"><Action aria-label={`${goal.pinned ? "Unpin" : "Pin"} goal ${goal.name}`} aria-pressed={goal.pinned} disabled={busy} onClick={() => void onSave({ type: "goal-card", id: goal.id, pinned: !goal.pinned })}><Pin size={14} /></Action><Action aria-label={`Move goal ${goal.name} up`} disabled={busy} onClick={() => void onSave({ type: "goal-card", id: goal.id, direction: "up" })}><ArrowUp size={14} /></Action><Action aria-label={`Move goal ${goal.name} down`} disabled={busy} onClick={() => void onSave({ type: "goal-card", id: goal.id, direction: "down" })}><ArrowDown size={14} /></Action><Action disabled={busy} onClick={() => void onSave({ type: "goal-card", id: goal.id, hidden: !goal.hidden })}>{goal.hidden ? "Show card" : "Hide card"}</Action><Action onClick={() => setDetail(goal.id)}>Details</Action></div>
      {reminder && <div role="status" className="space-y-2 rounded-2xl border p-3"><p className="text-sm">{evaluation.value === null ? "Your goal needs a recorded update." : evaluation.rule.metric === "balance" ? "Review your last recorded balance and its coverage." : `${amount(evaluation, evaluation.remaining, tracker.hideAmounts)} remains in recorded data.`} Missing logs are not proof you did not act.</p><div className="flex flex-wrap gap-2"><Action disabled={busy} onClick={() => void onSave({ type: "goal-reminder", id: goal.id, key: reminder, action: "dismiss", until: null })}>Dismiss this reminder</Action><Action disabled={busy} onClick={() => void onSave({ type: "goal-reminder", id: goal.id, key: reminder, action: "snooze", until: new Date(Date.now() + 3600000).toISOString() })}>Snooze 1 hour</Action><Action disabled={busy} onClick={() => void onSave({type:"goal-card",id:goal.id,lifecycle:"paused"})}>Pause goal</Action><Action onClick={() => setEditor(goal)}>Change goal / reminder</Action></div></div>}
    </Panel>; })}</div>
    {sourcesOpen && <SourceManager bundle={bundle} busy={busy} onSave={onSave} onClose={() => setSourcesOpen(false)} onCorrect={(goalId, initial) => setRecord({goalId,initial})} />}
    {editor && <GoalEditor key={editor === "new" ? "new" : editor.id} initial={editor === "new" ? null : editor} bundle={bundle} busy={busy} onSave={onSave} onMoney={onMoney} onClose={() => setEditor(null)} />}
    {selected && evaluation && <GoalDetails goal={selected} evaluation={evaluation} bundle={bundle} busy={busy} onSave={onSave} onClose={() => setDetail(null)} onEdit={() => { setDetail(null); setEditor(selected); }} onMoney={onMoney} onDelete={() => setDeleting(selected)} onRecord={initial => setRecord({ goalId: selected.id, initial })} />}
    {record && recordingGoal && recordingScope && <RecordEditor key={record.initial?.id ?? recordingScope.id} scope={recordingScope} evaluation={recordingGoal} data={bundle.record.data} initial={record.initial} busy={busy} onSave={onSave} onClose={() => setRecord(null)} />}
    {deleting && <Confirm title={`Delete ${deleting.name}?`} description="Removes this goal definition, calculation history and reminders only. Shared manual source records, savings allocations, tasks, events, workouts and written reviews remain. Remove source records separately in their detail controls." onClose={() => setDeleting(null)} onConfirm={async () => { if (!await onSave({ type: "goal-delete", id: deleting.id })) throw new Error("Save failed — retry"); setDetail(null); }} />}
  </section>;
}

export default function GoalTrackerPanel(props: { bundle: MomentumBundle; busy: boolean; onSave: (command: MomentumCommand) => Promise<boolean>; onMoney: () => void; error: string; onRetry: () => void }) {
  return <SaveContext.Provider value={{error:props.error,retry:props.onRetry,busy:props.busy}}><GoalTrackerBody {...props} /></SaveContext.Provider>; }
function SourceManager({bundle,busy,onSave,onClose,onCorrect}: {bundle:MomentumBundle;busy:boolean;onSave:(command:MomentumCommand)=>Promise<boolean>;onClose:()=>void;onCorrect:(goalId:string,record:GoalRecord)=>void}) {
  const tracker=trackerFor(bundle.record.data), [remove,setRemove]=useState<GoalRecord|null>(null),[scope,setScope]=useState<GoalScope|null>(null);
  return <><Sheet open full title="Manual record sources" description="Dated records remain here after a goal card is deleted. Shared records recalculate every linked goal." onClose={onClose}><SaveError /><div className="space-y-4">{tracker.scopes.filter(x=>bundle.record.data.preferences.money || x.kind === "activity").map(item=>{const evaluation=bundle.goalEvaluations?.find(x=>x.rule.scopeId===item.id),used=tracker.goals.some(x=>x.versions.some(v=>v.rule.scopeId===item.id));return <Panel key={item.id} className="space-y-3"><h3 className="font-semibold">{item.name}</h3><p className="text-xs text-muted-foreground">{item.kind} · {item.currency??"duration / visits"} · manually recorded</p>{tracker.records.filter(x=>x.scopeId===item.id).map(record=><div key={record.id} className="flex flex-wrap items-center justify-between gap-2 rounded-2xl border p-3"><p className="text-sm">{record.date} · {record.reference} · {record.kind}{item.currency ? tracker.hideAmounts ? " · ••••" : ` · ${formatMoney(record.value,item.currency)}` : record.kind === "duration" ? ` · ${record.value/60} min` : " · 1 visit"}</p><div className="flex flex-wrap gap-2">{evaluation && <Action disabled={busy} onClick={()=>onCorrect(evaluation.goalId,record)}>Correct</Action>}<Action disabled={busy} aria-label={`Remove record ${record.reference}`} onClick={()=>setRemove(record)}><Trash2 size={16}/></Action></div></div>)}<Action disabled={busy||used} onClick={()=>setScope(item)}>Delete unused scope and its records</Action>{used&&<p className="text-xs text-muted-foreground">Current or historical rules use this source. Individual records can still be corrected or removed.</p>}</Panel>;})}</div></Sheet>{remove&&<Confirm title="Remove this actual record?" description="Linked goals and affected periods recalculate. Personal reviews remain unchanged." onClose={()=>setRemove(null)} onConfirm={async()=>{if(!await onSave({type:"goal-remove-record",id:remove.id}))throw new Error("Save failed — retry");}}/>}{scope&&<Confirm title={`Delete ${scope.name} and its records?`} description="Permanently removes this unused manual source and its dated records. Other tools and scopes remain." onClose={()=>setScope(null)} onConfirm={async()=>{if(!await onSave({type:"goal-remove-scope",id:scope.id}))throw new Error("Save failed — retry");}}/>}</>;
}
