"use client";
import { useState } from "react";
import { Plus, ChevronDown, Link2, Pencil, Pause, Play, Archive, Trash2 } from "lucide-react";
import { areas, type Activity, type Chapter, type Journey, type MomentumData, type SourceRef } from "@/lib/momentum/types";
import { chapterDone, sourceKey } from "@/lib/momentum/logic";
import { journeyDraft, journeyTemplates } from "@/lib/momentum/content";
import type { MomentumCommand } from "@/lib/momentum/validation";
import { Action, Field, Picker, Notes, Panel, Sheet, Confirm, Empty, StepMark, SourceLink, Expand } from "./MomentumUI";
import ActionChooser from "./ActionChooser";
function JourneyEditor({ initial, busy, onSave, onClose }: { initial: Journey; busy: boolean; onSave: (value: Journey) => Promise<boolean>; onClose: () => void }) {
  const [value, setValue] = useState(() => structuredClone(initial));
  const patch = (change: Partial<Journey>) => setValue(current => ({ ...current, ...change }));
  return <Sheet open full title={initial.title ? "Edit your journey" : "Choose a direction"} description="Start with one primary journey and an optional secondary one. These are editable steps, not a transformation promise." onClose={onClose}><form className="space-y-5" onSubmit={async event => { event.preventDefault(); if (await onSave(value)) onClose(); }}>
    <div className="grid gap-4 sm:grid-cols-2"><Field label="Journey title" value={value.title} required maxLength={200} onChange={event => patch({ title: event.target.value })} /><Picker label="Area" value={value.area} options={areas} onChange={area => patch({ area: area as Journey["area"] })} /><Picker label="Goal type" value={value.kind} options={["project", "recurring", "learning", "money"]} onChange={kind => patch({ kind: kind as Journey["kind"] })} /><Picker label="Priority" value={value.priority} options={["primary", "secondary", "later"]} onChange={priority => patch({ priority: priority as Journey["priority"] })} /><Field label="Recognizable outcome" value={value.outcome} maxLength={3000} onChange={event => patch({ outcome: event.target.value })} /><Field label="Next action" value={value.nextAction} maxLength={3000} onChange={event => patch({ nextAction: event.target.value })} /><Field label="Target date (optional)" type="date" value={value.targetDate ?? ""} onChange={event => patch({ targetDate: event.target.value || null })} /><Field label={value.kind === "money" ? "Optional target with currency (e.g. 500 PLN)" : "Measurable target (optional, e.g. 2 reading sessions/week)"} value={value.target} maxLength={3000} onChange={event => patch({ target: event.target.value })} /></div>
    <Notes label="Personal reason" value={value.reason} maxLength={3000} onChange={event => patch({ reason: event.target.value })} /><h3 className="font-semibold">Your chapter path</h3><p className="text-sm text-muted-foreground">Edit the template before activating it. Link existing activities after saving, or use clearly labeled personal confirmation.</p>
    {value.chapters.map((chapter, index) => <fieldset key={chapter.id} className="space-y-3 rounded-2xl border p-4"><legend className="px-2 text-sm">Chapter {index + 1}</legend><Field label={`Chapter ${index + 1} title`} required value={chapter.title} maxLength={200} onChange={event => patch({ chapters: value.chapters.map(item => item.id === chapter.id ? { ...item, title: event.target.value } : item) })} /><Field label={`Chapter ${index + 1} completion criterion`} required value={chapter.criterion} maxLength={200} onChange={event => patch({ chapters: value.chapters.map(item => item.id === chapter.id ? { ...item, criterion: event.target.value } : item) })} /><div className="flex flex-wrap gap-2"><Action disabled={index === 0} aria-label={`Move chapter ${index + 1} up`} onClick={() => { const next = [...value.chapters]; [next[index - 1], next[index]] = [next[index], next[index - 1]]; patch({ chapters: next }); }}>Move up</Action><Action disabled={index === value.chapters.length - 1} onClick={() => { const next = [...value.chapters]; [next[index + 1], next[index]] = [next[index], next[index + 1]]; patch({ chapters: next }); }}>Move down</Action><Action disabled={value.chapters.length === 1} onClick={() => patch({ chapters: value.chapters.filter(item => item.id !== chapter.id) })}>Remove chapter</Action></div></fieldset>)}
    <Action onClick={() => patch({ chapters: [...value.chapters, { id: crypto.randomUUID(), title: "", criterion: "", links: [], confirmedAt: null }] })} disabled={value.chapters.length >= 30}><Plus size={16} />Add chapter</Action><div className="flex gap-2"><Action type="submit" tone="orange" disabled={busy}>Save journey</Action><Action onClick={onClose}>Cancel</Action></div>
  </form></Sheet>;
}
function JourneyCard({ journey, activities, busy, onSave, onEdit, onLink, onDelete, onCreateStep }: { journey: Journey; activities: Activity[]; busy: boolean; onSave: (command: MomentumCommand) => Promise<boolean>; onEdit: () => void; onLink: (chapter: Chapter) => void; onDelete: () => void; onCreateStep: (chapter: Chapter) => Promise<void> }) {
  const [open, setOpen] = useState(false), done = journey.chapters.filter(chapter => chapterDone(chapter, activities)).length, next = journey.chapters.find(chapter => !chapterDone(chapter, activities));
  return <Panel className="space-y-4"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><p className="mb-2 text-xs uppercase tracking-widest text-primary-plus">{journey.area} · {journey.priority} · {journey.status}</p><h3 className="break-words text-xl font-semibold">{journey.title}</h3></div><Action aria-label={`Edit ${journey.title}`} onClick={onEdit}><Pencil size={16} /></Action></div>{journey.reason && <p className="text-sm text-muted-foreground">{journey.reason}</p>}<p className="text-sm">{journey.outcome}</p><p className="font-medium text-primary-minus">{done} of {journey.chapters.length} steps completed</p>{journey.target && <p className="text-sm text-muted-foreground">Your target: {journey.target}{journey.targetDate && ` · ${journey.targetDate}`}</p>}
    {next && <div className="rounded-2xl border border-dashed p-4"><p className="text-xs text-muted-foreground">Next milestone</p><p className="mt-1 font-medium">{next.title}</p><p className="mt-1 text-sm text-muted-foreground">{next.criterion}</p></div>}
    <Action aria-expanded={open} aria-controls={`chapters-${journey.id}`} onClick={() => setOpen(!open)}><ChevronDown size={16} />{open ? "Hide chapters" : "Open chapter path"}</Action>
    <Expand id={`chapters-${journey.id}`} open={open}><ol className="momentum-chapter-path space-y-4">{journey.chapters.map(chapter => <li key={chapter.id} className="relative space-y-3 rounded-2xl border p-4"><div className="flex gap-3"><StepMark done={chapterDone(chapter, activities)} /><div className="min-w-0"><h4 className="break-words font-medium">{chapter.title}</h4><p className="mt-1 text-sm text-muted-foreground">{chapter.criterion}</p></div></div>
      {chapter.links.map(ref => { const activity = activities.find(item => item.key === sourceKey(ref)); return <div key={sourceKey(ref)} className="flex flex-wrap items-center gap-2 text-sm">{activity ? <><span className="break-words">{activity.title} · {activity.status}</span><SourceLink activity={activity} /></> : <span className="text-muted-foreground">Source removed or unavailable · progress not confirmed</span>}<Action disabled={busy} onClick={() => void onSave({ type: "chapter", journeyId: journey.id, chapterId: chapter.id, links: chapter.links.filter(item => sourceKey(item) !== sourceKey(ref)) })}>Unlink</Action></div>; })}
      {!chapter.links.length && <p className="text-xs text-muted-foreground">{chapter.confirmedAt ? "User-confirmed completion" : "No source evidence linked. Personal confirmation is available."}</p>}
      <div className="flex flex-wrap gap-2"><Action disabled={busy} onClick={() => onLink(chapter)}><Link2 size={16} />Link existing action</Action>{!chapter.links.length && <><Action tone={chapter.confirmedAt ? "neutral" : "orange"} disabled={busy || journey.status !== "active"} onClick={() => void onSave({ type: "chapter", journeyId: journey.id, chapterId: chapter.id, confirm: !chapter.confirmedAt })}>{chapter.confirmedAt ? "Undo personal confirmation" : "I confirm this criterion"}</Action><Action disabled={busy || journey.status !== "active"} onClick={() => void onCreateStep(chapter)}>Create a To-Do step</Action></>}</div>
    </li>)}</ol></Expand>
    <div className="flex flex-wrap gap-2"><Action disabled={busy} onClick={() => void onSave({ type: "journey", value: { ...journey, status: journey.status === "active" ? "paused" : "active" } })}>{journey.status === "active" ? <Pause size={16} /> : <Play size={16} />}{journey.status === "active" ? "Pause" : "Resume"}</Action><Action disabled={busy} onClick={() => void onSave({ type: "journey", value: { ...journey, status: "archived" } })}><Archive size={16} />Archive</Action><Action disabled={busy} aria-label={`Delete journey ${journey.title}`} onClick={onDelete}><Trash2 size={16} /></Action></div>
  </Panel>;
}
export default function Journeys({ data, activities, busy, onSave, onCreate }: { data: MomentumData; activities: Activity[]; busy: boolean; onSave: (command: MomentumCommand) => Promise<boolean>; onCreate: (id: string, content: string) => Promise<boolean> }) {
  const [editor, setEditor] = useState<Journey | null>(null), [link, setLink] = useState<{ journey: Journey; chapter: Chapter } | null>(null), [deleting, setDeleting] = useState<Journey | null>(null), [archived, setArchived] = useState(false);
  const items = data.journeys.filter(item => archived || item.status !== "archived");
  return <div className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-semibold">A direction you chose</h2><p className="mt-1 text-sm text-muted-foreground">One primary journey. One optional secondary. Other ideas can wait.</p></div><Action tone="blue" onClick={() => setEditor(journeyDraft(null, () => crypto.randomUUID()))}><Plus size={16} />New journey</Action></div>
    {!!data.journeys.length && <Action aria-pressed={archived} onClick={() => setArchived(!archived)}>{archived ? "Hide archived" : "Include archived"}</Action>}
    {items.length ? <div className="grid items-start gap-4 xl:grid-cols-2">{items.map(journey => <div key={journey.id} id={`journey-${journey.id}`} className="scroll-mt-8 space-y-3">{data.tracker?.goals.filter(goal => goal.versions.at(-1)?.rule.journeyId === journey.id && (data.preferences.money || !goal.versions.some(version => version.rule.currency))).map(goal => <a key={goal.id} href="/account/momentum#goal-tracker" className="inline-flex min-h-11 items-center rounded-2xl border px-3 text-sm text-primary-plus">Tracked goal: {goal.name} · open Goal Tracker</a>)}<JourneyCard key={journey.id} journey={journey} activities={activities} busy={busy} onSave={onSave} onEdit={() => setEditor(journey)} onLink={chapter => setLink({ journey, chapter })} onDelete={() => setDeleting(journey)} onCreateStep={async chapter => { const id = `momentum:chapter:${chapter.id}`; if (await onCreate(id, chapter.title)) await onSave({ type: "chapter", journeyId: journey.id, chapterId: chapter.id, links: [{ kind: "task", id }] }); }} /></div>)}</div> : <Empty>No journey required to use Momentum. Pick a task in Today, or shape a direction below.</Empty>}
    <div><h3 className="mb-3 font-semibold">Optional starting structures</h3><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{journeyTemplates.filter(item => data.preferences.money || item.area !== "Money").map(template => <button type="button" key={template.key} className="momentum-source-choice rounded-2xl border bg-card/20 p-5 text-left" onClick={() => setEditor(journeyDraft(template.key, () => crypto.randomUUID()))}><p className="mb-2 text-xs text-primary-plus">{template.area}</p><h4 className="font-semibold">{template.title}</h4><p className="mt-2 text-sm text-muted-foreground">{template.chapters.length} editable chapters · review before saving</p></button>)}</div></div>
    {editor && <JourneyEditor key={editor.id} initial={editor} busy={busy} onClose={() => setEditor(null)} onSave={value => onSave({ type: "journey", value })} />}
    {link && <ActionChooser title={`Link: ${link.chapter.title}`} linksOnly activities={activities} journeys={data.journeys} busy={busy} onClose={() => setLink(null)} onCreate={onCreate} onSelect={selection => onSave({ type: "chapter", journeyId: link.journey.id, chapterId: link.chapter.id, links: [...link.chapter.links.filter(ref => sourceKey(ref) !== sourceKey(selection.source)), selection.source as SourceRef] })} />}
    {deleting && <Confirm title="Delete this journey?" description="Its chapters and personal reason will be removed. Linked tasks, events, workouts and savings records will remain in their original tools." onClose={() => setDeleting(null)} onConfirm={async () => { if (!await onSave({ type: "delete-journey", id: deleting.id })) throw new Error("Save failed — retry from Momentum."); }} />}
  </div>;
}
