"use client";
import { useRef, useState } from "react";
import Link from "next/link";
import { AnimatePresence, MotionConfig } from "framer-motion";
import { ArrowRight, Bookmark, Check, Compass, Plus, Settings2, Sparkles, Timer, X } from "lucide-react";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/app/components/ui/tabs";
import { useMomentum } from "@/hooks/use-momentum";
import { exportMomentum, momentumTask } from "@/lib/actions/momentum.actions";
import { localDate, dateLabel, dateInZone, weekStart } from "@/lib/gym/dates";
import { thoughts } from "@/lib/momentum/content";
import { chapterDone, milestoneKeys, sourceKey, suggestion, formatMoney, savingsBalance } from "@/lib/momentum/logic";
import type { Activity, MomentumBundle, Selection } from "@/lib/momentum/types";
import { Action, Sheet, Field, Panel, Reveal, SourceLabel, SourceLink, Empty, Confirm, StepMark } from "./MomentumUI";
import ActionChooser from "./ActionChooser";
import Journeys from "./Journeys";
import FocusPanel, { FocusStarter } from "./FocusPanel";
import WeeklyReview from "./WeeklyReview";
import MoneyJournal from "./MoneyJournal";
import GoalTrackerPanel from "./GoalTrackerPanel";
import RecentWins from "./RecentWins";
import AppLoading from "@/app/components/shared/AppLoading";
import { trackerFor } from "@/lib/momentum/goals/evaluate";

function Mission({ selection, bundle, busy, small, onFocus, onRemove, onChange, onComplete }: { selection: Selection; bundle: MomentumBundle; busy: boolean; small?: boolean; onFocus: () => void; onRemove: () => void; onChange: () => void; onComplete?: () => void }) {
  const activity = bundle.activities.find(item => item.key === sourceKey(selection.source)), journey = bundle.record.data.journeys.find(item => item.id === selection.journeyId), upcoming = activity?.date && activity.date > bundle.today;
  return <Panel className={`space-y-4 ${small ? "" : "momentum-accent-blue"}`}><div className="flex items-start justify-between gap-3"><p className="text-xs uppercase tracking-widest text-primary-plus">{small ? "Supporting action" : "Your next move"}</p><Action disabled={busy} aria-label={small ? "Remove supporting selection" : "Remove main selection"} onClick={onRemove}><X size={15} /></Action></div>{!activity ? <Empty>The source action was removed or is unavailable. Change your selection; its history has not been replaced.</Empty> : <><SourceLabel activity={activity} /><h2 className={`${small ? "text-lg" : "text-2xl sm:text-3xl"} break-words font-semibold leading-tight`}>{activity.title}</h2>{selection.why && <p className="text-sm text-muted-foreground">{selection.why}</p>}{journey && <p className="text-sm text-primary-plus">{journey.title} · {journey.status}</p>}<p className="text-sm text-muted-foreground">{activity.date ? `Date: ${dateLabel(activity.date)}` : "Choose when to begin"}{activity.time && ` · ${activity.time}`}{(selection.minutes ?? activity.minutes) && ` · approximately ${selection.minutes ?? activity.minutes} min`}</p>
    <div className="flex flex-wrap gap-2">{activity.status === "completed" ? <SourceLink activity={activity}>View completed result</SourceLink> : activity.ref.kind === "task" && !upcoming ? <Action tone="orange" disabled={busy} onClick={onFocus}><Timer size={16} />Start 10 minutes</Action> : <SourceLink activity={activity}>{activity.ref.kind === "workout" ? activity.status === "active" ? "Continue workout" : "Open planned workout" : activity.ref.kind === "task" ? "Open scheduled task" : "Open event"}</SourceLink>}<Action disabled={busy} onClick={onChange}>Change selection</Action></div>{activity.ref.kind === "task" && activity.status !== "completed" && <div className="flex flex-wrap gap-2"><SourceLink activity={activity}>Open task</SourceLink><Action disabled={busy} onClick={() => { if (onComplete) onComplete(); else onFocus(); }}>{onComplete ? "Mark task completed" : "Log focus before completing"}</Action></div>}{activity.status === "completed" && <p className="flex items-center gap-2 text-sm text-primary-minus"><Check size={16} />Completed in its source tool</p>}</>}
  </Panel>;
}
function Easier({ selection, activity, busy, onCreate, onSelect, onExternal, onSave, onChoose, onClose }: { selection: Selection | null; activity: Activity | undefined; busy: boolean; onCreate: (id: string, title: string) => Promise<boolean>; onSelect: (selection: Selection) => Promise<boolean>; onExternal: ReturnType<typeof useMomentum>["external"]; onSave: ReturnType<typeof useMomentum>["save"]; onChoose: () => void; onClose: () => void }) {
  const [title, setTitle] = useState(""), [date, setDate] = useState(localDate()), [id] = useState(() => crypto.randomUUID()), [mode, setMode] = useState("choose"), [preview, setPreview] = useState(false);
  return <Sheet open title="Make today easier" description="A deliberate adjustment keeps past work and original records intact." onClose={onClose}><div className="flex flex-wrap gap-2"><Action onClick={() => setMode("smaller")}>Start with a smaller step</Action><Action onClick={() => setMode("shorter")}>Shorten focus</Action><Action onClick={() => setMode("move")}>Move to another day</Action><Action onClick={onChoose}>Different main mission</Action><Action disabled={busy} onClick={async () => { if (await onSave({ type: "rest", value: true })) onClose(); }}>Keep a planned rest day</Action></div>
    {mode === "smaller" && <form className="space-y-3" onSubmit={async event => { event.preventDefault(); if (!preview) { setPreview(true); return; } if (await onCreate(id, title) && await onSelect({ source: { kind: "task", id }, why: "Smaller step; the original action remains unchanged", minutes: 10, journeyId: selection?.journeyId ?? null })) { await onSave({ type: "adjustment", id, kind: "smaller-step" }); onClose(); } }}><Field label="Name the smaller step" required maxLength={3000} value={title} onChange={event => { setTitle(event.target.value); setPreview(false); }} />{preview && <Empty>Create “{title}” as a separate To-Do task and select it. Completing it will not complete {activity ? `“${activity.title}”` : "the original action"}.</Empty>}<Action type="submit" tone="orange" disabled={busy}>{preview ? "Create and choose this step" : "Preview smaller step"}</Action></form>}
    {mode === "shorter" && <div className="space-y-3"><Empty>Choose a shorter timer here. Your task and planned targets stay unchanged. For a workout, open Gym to review adaptations before saving them.</Empty><FocusStarter source={activity?.ref.kind === "task" ? activity.ref : null} busy={busy} onSave={async command => { const ok = await onSave(command); if (ok) onClose(); return ok; }} />{activity?.ref.kind === "workout" && <SourceLink activity={activity}>Review workout in Gym</SourceLink>}</div>}
    {mode === "move" && <div className="space-y-3">{activity?.ref.kind === "task" ? <><Field label="New task date" type="date" value={date} onChange={event => { setDate(event.target.value); setPreview(false); }} /><Empty>{preview ? `Set the task’s due date to ${date}. The task stays open and your existing selection remains available to change or remove.` : "Preview a new due date before saving. This changes the canonical To-Do task; no copy is created."}</Empty><Action disabled={busy || !date} tone="orange" onClick={async () => { if (!preview) { setPreview(true); return; } if (await onExternal(() => momentumTask({ action: "reschedule", id: activity.ref.id, date }))) { await onSave({ type: "adjustment", id, kind: "rescheduled" }); onClose(); } }}>{preview ? "Confirm new date" : "Preview move"}</Action></> : activity ? <><Empty>Open the source planner to preview the move, preserve optional times, and check scheduling conflicts before confirming.</Empty><SourceLink activity={activity}>Review schedule in {activity.ref.kind === "workout" ? "Gym" : "Events"}</SourceLink></> : <Empty>Choose an action first. Its existing planner will handle scheduling.</Empty>}</div>}
    {mode === "choose" && <Empty>Choose the adjustment that fits today. Rest never resets your journey.</Empty>}
  </Sheet>;
}
export default function MomentumClient() {
  const api = useMomentum(), { bundle, busy, loading, error, status, celebration } = api;
  const [tab, setTab] = useState("today"), [chooser, setChooser] = useState<"main" | "supporting" | null>(null), [customize, setCustomize] = useState(false), [favorites, setFavorites] = useState(false), [money, setMoney] = useState(false), [easier, setEasier] = useState(false), [focusVisible, setFocusVisible] = useState(false), [confirmDelete, setConfirmDelete] = useState(false), [exportError, setExportError] = useState("");
  const exportLock = useRef(false);
  if (loading || !bundle) return <div className="gym-scope space-y-5 rounded-3xl border p-6"><h1 className="text-3xl font-semibold">Momentum</h1>{loading ? <AppLoading label="Loading Momentum…" /> : <p role="status">{status}</p>}{error && <p role="alert">{error}</p>}{!loading && <Action onClick={() => void api.reload()}>Retry loading</Action>}</div>;
  const data = bundle.record.data, day = data.days.find(item => item.date === bundle.today), selection = day?.main ?? null, activity = selection ? bundle.activities.find(item => item.key === sourceKey(selection.source)) : undefined;
  const rest = day?.rest || bundle.restDays.includes(bundle.today), thought = data.thoughts.find(item => item.date === bundle.today), proposed = selection ? null : suggestion(data, bundle.activities, bundle.today, !!rest);
  const activeFocus = data.focus.find(item => ["running", "paused", "awaiting"].includes(item.status)), primaryJourney = data.journeys.find(item => item.status === "active" && item.priority === "primary"), nextChapter = primaryJourney?.chapters.find(chapter => !chapterDone(chapter, bundle.activities));
  const wins = bundle.activities.filter(item => item.status === "completed").sort((a, b) => (b.completedAt ?? b.date ?? "").localeCompare(a.completedAt ?? a.date ?? "")).slice(0, 4), visibleAwards = milestoneKeys(data, bundle.activities).filter(key => data.awards.some(item => item.key === key));
  const choose = (value: Selection) => api.save({ type: "select", slot: chooser ?? "main", selection: value });
  const create = (id: string, content: string) => api.external(() => momentumTask({ action: "create", id, content }));
  const complete = (id: string) => api.external(() => momentumTask({ action: "complete", id }));
  const thoughtAction = () => {
    if (!thought) return;
    if ([7, 10].includes(thought.index)) setTab("review");
    else if ([6, 11].includes(thought.index)) setEasier(true);
    else if (thought.index === 9) { if (data.preferences.money) setMoney(true); else setCustomize(true); }
    else setChooser("main");
  };
  return <MotionConfig reducedMotion="user"><div className="gym-scope momentum-scope space-y-6 pb-20"><header className="flex flex-wrap items-start justify-between gap-4"><div><p className="mb-2 flex items-center gap-2 text-xs uppercase tracking-[0.2em] text-primary-plus"><Compass size={15} />{dateLabel(bundle.today, { weekday: "long", month: "long", day: "numeric" })}</p><h1 className="text-3xl font-semibold sm:text-4xl">Momentum</h1><p className="mt-2 text-muted-foreground">One useful step at a time.</p></div><Action onClick={() => setCustomize(true)} aria-label="Customize Momentum"><Settings2 size={17} />Customize</Action></header>
    <div className="flex flex-wrap items-center gap-3"><p role="status" aria-live="polite" className="text-xs text-muted-foreground">{status}</p>{busy && <span className="text-xs">Please wait for the save.</span>}</div>{error && <div role="alert" className="space-y-2 rounded-2xl border p-4"><p className="text-sm">{error}</p><div className="flex flex-wrap gap-2"><Action disabled={busy} onClick={() => void api.retry()}>Retry save</Action><Action disabled={busy} onClick={() => void api.reload()}>Reload saved data</Action></div></div>}
    <Tabs value={tab} onValueChange={setTab}><TabsList className="mb-6 grid h-auto grid-cols-3 rounded-2xl p-1"><TabsTrigger value="today" className="min-h-11 rounded-xl">Today</TabsTrigger><TabsTrigger value="journeys" className="min-h-11 rounded-xl">Journeys</TabsTrigger><TabsTrigger value="review" className="min-h-11 rounded-xl">Weekly Review</TabsTrigger></TabsList>
      <TabsContent value="today" className="space-y-5">
        {data.preferences.thoughts && thought && !thought.dismissed && <Panel className="space-y-3" label="Daily thought"><p className="flex items-center gap-2 text-xs uppercase tracking-widest text-muted-foreground"><Sparkles size={14} />Daily thought · original app copy</p><p className="text-lg font-medium">{thoughts[thought.index][0]}</p><p className="text-sm text-muted-foreground">{thoughts[thought.index][1]}</p><div className="flex flex-wrap gap-2"><Action tone="blue" onClick={thoughtAction}>{thoughts[thought.index][2]}</Action><Action disabled={busy} aria-pressed={data.favorites.includes(thought.index)} onClick={() => void api.save({ type: "thought", action: data.favorites.includes(thought.index) ? "unsave" : "save", index: thought.index })}><Bookmark size={14} />{data.favorites.includes(thought.index) ? "Thought saved" : "Save thought"}</Action><Action disabled={busy} onClick={() => void api.save({ type: "thought", action: "dismiss", index: thought.index })}>Not relevant</Action></div><p className="text-xs text-muted-foreground">Save bookmarks this prompt in Customize → Saved thoughts. The action button opens a tool to put it into practice.</p></Panel>}
        <div className="grid items-start gap-5 xl:grid-cols-[minmax(0,1.6fr)_minmax(270px,1fr)]"><div className="space-y-5"><Reveal key={selection ? sourceKey(selection.source) : "empty-mission"}>{selection ? <Mission onComplete={() => void complete(selection.source.id)} selection={selection} bundle={bundle} busy={busy} onFocus={() => { if (activeFocus) setFocusVisible(true); else void api.save({ type: "focus-start", id: crypto.randomUUID(), source: selection.source, minutes: 10 }); }} onChange={() => setChooser("main")} onRemove={() => void api.save({ type: "select", slot: "main", selection: null })} /> : <Panel className="space-y-4 momentum-accent-blue"><p className="text-xs uppercase tracking-widest text-primary-plus">Your next move</p><h2 className="text-2xl font-semibold">What would you like to move forward?</h2><p className="text-sm text-muted-foreground">Choose one useful action. A journey is optional.</p><div className="flex flex-wrap gap-2"><Action tone="orange" onClick={() => setTab("journeys")}>Choose a direction<ArrowRight size={16} /></Action><Action onClick={() => setChooser("main")}>Pick an existing task</Action></div>{proposed && <div className="space-y-3 rounded-2xl border border-dashed p-4"><p className="text-xs text-muted-foreground">Suggestion · {proposed.reason}</p><p className="font-medium">{proposed.activity.title}</p><Action disabled={busy} tone="blue" onClick={() => void api.save({ type: "select", slot: "main", selection: { source: proposed.activity.ref, why: proposed.reason, minutes: proposed.activity.minutes, journeyId: proposed.journeyId } })}>Choose this action</Action></div>}</Panel>}</Reveal>
          <div className="flex flex-wrap gap-2"><Action onClick={() => setEasier(true)}>Make today easier</Action><Action disabled={(day?.supporting.length ?? 0) >= 2} onClick={() => setChooser("supporting")}><Plus size={16} />Supporting action</Action>{!activeFocus && <Action onClick={() => setFocusVisible(!focusVisible)}><Timer size={16} />{focusVisible ? "Hide focus setup" : "Focus session"}</Action>}</div>
          {rest && <Panel className="space-y-2"><h3 className="font-medium">A deliberate rest day</h3><p className="text-sm text-muted-foreground">Your journey stays intact. Workout suggestions are held back today; existing plans remain in Gym.</p>{day?.rest && <Action disabled={busy} onClick={() => void api.save({ type: "rest", value: false })}>Remove Momentum rest choice</Action>}</Panel>}
          {day?.supporting.map(item => <Mission key={sourceKey(item.source)} small onComplete={() => void complete(item.source.id)} selection={item} bundle={bundle} busy={busy} onFocus={() => { if (activeFocus) setFocusVisible(true); else void api.save({ type: "focus-start", id: crypto.randomUUID(), source: item.source, minutes: 10 }); }} onRemove={() => void api.save({ type: "select", slot: "supporting", selection: null, removeKey: sourceKey(item.source) })} onChange={() => setChooser("supporting")} />)}
          {activeFocus ? <FocusPanel key={`${activeFocus.id}:${activeFocus.status}`} focus={activeFocus} activities={bundle.activities} busy={busy} onSave={api.save} onComplete={complete} /> : focusVisible && <FocusStarter source={activity?.ref.kind === "task" ? activity.ref : null} busy={busy} onSave={api.save} />}
          <GoalTrackerPanel error={error} onRetry={() => void api.retry()} bundle={bundle} busy={busy} onSave={api.save} onMoney={() => setMoney(true)} />
        </div><div className="space-y-5"><Panel className="space-y-4"><p className="text-xs uppercase tracking-widest text-primary-plus">Current journey</p>{primaryJourney ? <><h3 className="text-xl font-semibold">{primaryJourney.title}</h3><p className="text-sm text-muted-foreground">{primaryJourney.chapters.filter(chapter => chapterDone(chapter, bundle.activities)).length} of {primaryJourney.chapters.length} steps completed</p>{nextChapter ? <div className="flex gap-3"><StepMark done={false} /><div><p className="font-medium">{nextChapter.title}</p><p className="mt-1 text-sm text-muted-foreground">{nextChapter.criterion}</p></div></div> : <p className="text-primary-minus">The chosen chapter criteria are complete.</p>}<Action onClick={() => setTab("journeys")}>Open chapter path</Action></> : <><Empty>Your actions can stand on their own. Add a direction when it helps.</Empty><Action onClick={() => setTab("journeys")}>Explore journeys</Action></>}</Panel>
          <RecentWins wins={wins} milestones={data.preferences.rewards ? visibleAwards.length : 0} />
          {data.preferences.rewards && trackerFor(data).attainments.length > 0 && <Panel className="space-y-3"><h3 className="font-semibold">Recorded goal thresholds</h3>{trackerFor(data).attainments.slice(-3).reverse().map(item => { const goal = trackerFor(data).goals.find(goal => item.key.startsWith(`${goal.id}:`)), result = trackerFor(data).history.find(value => item.key === `${value.goalId}:${value.key}`); if (!goal || !result || !data.preferences.money && goal.versions.some(v => v.rule.currency)) return null; return <div key={item.key} className="text-sm"><p>{goal.name} · {result.start} – {result.end ?? "ongoing"}</p><p className="mt-1 text-xs text-muted-foreground">Threshold first recorded {dateLabel(dateInZone(new Date(item.at), bundle.timezone))}. Current result: {result.status}{result.revisedAt ? " · revised after correction" : ""}. No repeat reward.</p></div>; })}</Panel>}
          {!data.reviews.some(item => item.week === weekStart(bundle.today) && !item.draft) && <Panel className="space-y-3"><h3 className="font-semibold">A short weekly review</h3><p className="text-sm text-muted-foreground">Notice what helped. Choose one adjustment if you need it.</p><Action onClick={() => setTab("review")}>Review this week</Action></Panel>}
          {data.preferences.money && <Panel className="space-y-3"><h3 className="font-semibold">Money · your own purpose</h3>{data.savings.slice(0, 2).map(goal => <p key={goal.id} className="text-sm">{goal.name} · {formatMoney(savingsBalance(goal), goal.currency)} allocated</p>)}{!data.savings.length && <p className="text-sm text-muted-foreground">Optional savings journal, separate from spending and portfolio values.</p>}<Action onClick={() => setMoney(true)}>Open money journal</Action></Panel>}
        </div></div>
      </TabsContent>
      <TabsContent value="journeys"><Journeys data={data} activities={bundle.activities} busy={busy} onSave={api.save} onCreate={create} /></TabsContent>
      <TabsContent value="review"><WeeklyReview data={data} activities={bundle.activities} onComplete={complete} today={bundle.today} busy={busy} onSave={api.save} onChoose={() => { setTab("today"); setChooser("main"); }} /></TabsContent>
    </Tabs>
    <AnimatePresence>{celebration && <Reveal className="momentum-milestone rounded-2xl border p-4"><div role="status" className="flex flex-wrap items-center justify-between gap-3"><span className="flex items-center gap-2"><Sparkles size={18} />A milestone saved. Keep the next step yours.</span><Action onClick={api.dismissCelebration}>Dismiss</Action></div></Reveal>}</AnimatePresence>
    {chooser && <ActionChooser title={chooser === "main" ? "Choose your next move" : "Choose a supporting action"} activities={bundle.activities} journeys={data.journeys} busy={busy} onClose={() => setChooser(null)} onSelect={choose} onCreate={create} />}
    {easier && <Easier selection={selection} activity={activity} busy={busy} onCreate={create} onSelect={value => api.save({ type: "select", slot: "main", selection: value })} onSave={api.save} onExternal={api.external} onChoose={() => { setEasier(false); setChooser("main"); }} onClose={() => setEasier(false)} />}
    {customize && <Sheet open title="Keep Momentum useful for you" description="Private account preferences. Optional areas never gate your tools." onClose={() => setCustomize(false)}><div className="space-y-4">{([['thoughts', 'Daily thought'], ['money', 'Money area'], ['statistics', 'Detailed weekly numbers'], ['rewards', 'Small milestone feedback']] as const).map(([key, label]) => <label key={key} className="flex min-h-12 cursor-pointer items-center justify-between gap-4 rounded-2xl border p-3"><span>{label}</span><input type="checkbox" className="h-5 w-5 accent-[var(--primary-plus)]" checked={data.preferences[key]} disabled={busy} onChange={event => void api.save({ type: "preferences", value: { ...data.preferences, [key]: event.target.checked } })} /></label>)}<Action onClick={() => { setCustomize(false); setFavorites(true); }}>Saved thoughts</Action><Action disabled={busy} onClick={async () => { if (exportLock.current) return; exportLock.current = true; try { const file = await exportMomentum(), url = URL.createObjectURL(new Blob([JSON.stringify(file, null, 2)], { type: "application/json" })), anchor = document.createElement("a"); anchor.href = url; anchor.download = `momentum-${bundle.today}.json`; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); setExportError(""); } catch { setExportError("Export failed — retry."); } finally { exportLock.current = false; } }}>Export my Momentum records</Action><Action disabled={busy} onClick={() => setConfirmDelete(true)}>Delete Momentum records</Action>{exportError && <p role="alert">{exportError}</p>}<p className="text-xs text-muted-foreground">Account-owned database storage. Reflections are private. Export covers this module; source records remain in To-Do, Gym, Events and Finance.</p></div></Sheet>}
    {favorites && <Sheet open title="Saved thoughts" description="Original app copy, saved by you. No invented quote attributions." onClose={() => setFavorites(false)}>{data.favorites.length ? data.favorites.map(index => <Panel key={index} className="space-y-3"><p>{thoughts[index][0]}</p><p className="text-sm text-muted-foreground">{thoughts[index][1]}</p><Action disabled={busy} onClick={() => void api.save({ type: "thought", action: "unsave", index })}>Remove saved thought</Action></Panel>) : <Empty>No saved thoughts yet.</Empty>}</Sheet>}
    {money && <MoneyJournal goals={data.savings} today={bundle.today} busy={busy} onSave={api.save} onClose={() => setMoney(false)} />}
    {confirmDelete && <Confirm title="Delete all Momentum records?" description="Journeys, private reflections, selections, focus logs, preferences and savings journal entries will be cleared. Original tasks, events, workouts, investments and Finance records will remain. This cannot be undone unless you exported a copy." onClose={() => setConfirmDelete(false)} onConfirm={async () => { if (!await api.save({ type: "delete-all" })) throw new Error("Save failed — retry."); setCustomize(false); }} />}
    <footer className="text-xs text-muted-foreground">Choose what matters. Take the next step. See what you are building. <Link className="text-primary-plus underline" href="/account">Account settings</Link></footer>
  </div></MotionConfig>;
}
