"use client";
import { useAccountPreferences } from "@/app/components/shared/account/AccountPreferencesProvider";
import { useState } from "react";
import Link from "next/link";
import { Plus, Pencil, Trash2 } from "lucide-react";
import { currencies, type SavingsGoal } from "@/lib/momentum/types";
import { formatMoney, moneyInput, parseMoney, savingsBalance } from "@/lib/momentum/logic";
import type { MomentumCommand } from "@/lib/momentum/validation";
import { Action, Field, Picker, Sheet, Panel, Confirm, Empty } from "./MomentumUI";
function GoalEditor({ initial, busy, onSave, onClose }: { initial: SavingsGoal; busy: boolean; onSave: (command: MomentumCommand) => Promise<boolean>; onClose: () => void }) {
  const [value, setValue] = useState(initial), [target, setTarget] = useState(moneyInput(initial.targetMinor, initial.currency)), [opening, setOpening] = useState(moneyInput(initial.openingMinor, initial.currency)), [error, setError] = useState("");
  return <Sheet open title="Your savings goal" description="A private allocation journal. Entries record money held elsewhere; no transfers are made." onClose={onClose}><form className="space-y-4" onSubmit={async event => { event.preventDefault(); try { const next = { ...value, targetMinor: parseMoney(target, value.currency), openingMinor: parseMoney(opening, value.currency) }; if (await onSave({ type: "savings", value: next })) onClose(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Check the amounts"); } }}><Field label="Goal name" required maxLength={200} value={value.name} onChange={event => setValue({ ...value, name: event.target.value })} /><Picker label="Currency" value={value.currency} options={currencies} disabled={!!initial.entries.length || initial.openingMinor > 0} onChange={currency => setValue({ ...value, currency: currency as SavingsGoal["currency"] })} /><Field label="Target amount" required inputMode="decimal" value={target} onChange={event => setTarget(event.target.value)} /><Field label="Opening allocated balance" required inputMode="decimal" value={opening} onChange={event => setOpening(event.target.value)} /><Field label="Opening balance as-of date" type="date" required value={value.openingDate} onChange={event => setValue({ ...value, openingDate: event.target.value })} /><Field label="Target date (optional)" type="date" value={value.targetDate ?? ""} onChange={event => setValue({ ...value, targetDate: event.target.value || null })} /><Action tone="orange" type="submit" disabled={busy}>Save goal</Action>{error && <p role="alert">{error}</p>}</form></Sheet>;
}
function EntryEditor({ goal, entry, today, busy, onSave, onClose }: { goal: SavingsGoal; entry: SavingsGoal["entries"][number] | null; today: string; busy: boolean; onSave: (command: MomentumCommand) => Promise<boolean>; onClose: () => void }) {
  const [value, setValue] = useState(entry ?? { id: crypto.randomUUID(), allocationRef: "", date: today, type: "contribution" as const, amountMinor: 0, note: "" }), [amount, setAmount] = useState(entry ? moneyInput(entry.amountMinor, goal.currency) : ""), [error, setError] = useState("");
  return <Sheet open title={entry ? "Correct journal entry" : "Record an allocation"} description={`Only ${goal.currency}. Record each real allocation once. If sharing money across goals, enter explicitly split amounts.`} onClose={onClose}><form className="space-y-4" onSubmit={async event => { event.preventDefault(); try { if (await onSave({ type: "entry", goalId: goal.id, value: { ...value, amountMinor: parseMoney(amount, goal.currency) } })) onClose(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Check the amount"); } }}><Picker label="Entry type" value={value.type} options={["contribution", "withdrawal"]} onChange={type => setValue({ ...value, type: type as typeof value.type })} /><Field label="Unique allocation reference" required maxLength={100} value={value.allocationRef} onChange={event => setValue({ ...value, allocationRef: event.target.value })} placeholder="transfer-03-Oct; split portions use separate references" /><Field label={`Amount (${goal.currency})`} value={amount} required inputMode="decimal" onChange={event => setAmount(event.target.value)} /><Field label="Allocation date" type="date" required min={goal.openingDate} max={today} value={value.date} onChange={event => setValue({ ...value, date: event.target.value })} /><Field label="Optional note" maxLength={3000} value={value.note} onChange={event => setValue({ ...value, note: event.target.value })} /><Action tone="orange" type="submit" disabled={busy}>Save journal entry</Action>{error && <p role="alert">{error}</p>}</form></Sheet>;
}
export default function MoneyJournal({ goals, today, busy, onSave, onClose }: { goals: SavingsGoal[]; today: string; busy: boolean; onSave: (command: MomentumCommand) => Promise<boolean>; onClose: () => void }) {
  const {settings}=useAccountPreferences();
  const [editor, setEditor] = useState<SavingsGoal | null>(null), [entry, setEntry] = useState<{ goal: SavingsGoal; entry: SavingsGoal["entries"][number] | null } | null>(null), [remove, setRemove] = useState<{ title: string; command: MomentumCommand } | null>(null);
  return <><Sheet open full title="Money with a purpose you chose" description="Private savings allocations, separate from spending and investment values. This journal never moves money or promises returns." onClose={onClose}><Action tone="blue" onClick={() => setEditor({ id: crypto.randomUUID(), name: "", currency: (currencies.find(currency => currency === settings.preferences.financeDefaultCurrency) ?? "USD"), targetMinor: 0, openingMinor: 0, openingDate: today, targetDate: null, entries: [] })}><Plus size={16} />New savings goal</Action>{!goals.length && <Empty>No savings goal yet. Choose your own amount and currency when it is useful.</Empty>}
    {goals.map(goal => <Panel key={goal.id} className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="text-lg font-semibold">{goal.name}</h3><div className="flex gap-2"><Action aria-label={`Edit ${goal.name}`} onClick={() => setEditor(goal)}><Pencil size={16} /></Action><Action aria-label={`Delete ${goal.name}`} onClick={() => setRemove({ title: "Delete this goal and its allocation journal? No Finance or investment records will be changed.", command: { type: "delete-savings", id: goal.id } })}><Trash2 size={16} /></Action></div></div><p className="text-2xl font-semibold text-primary-plus">{formatMoney(savingsBalance(goal), goal.currency)} <span className="text-sm font-normal text-muted-foreground">allocated of {formatMoney(goal.targetMinor, goal.currency)}</span></p><p className="text-xs text-muted-foreground">Opening {formatMoney(goal.openingMinor, goal.currency)} as of {goal.openingDate}{goal.targetDate && ` · target ${goal.targetDate}`}. Balance = opening + contributions − withdrawals.</p>{savingsBalance(goal) < 0 && <p className="text-sm">Recorded withdrawals exceed allocated funds. Check opening balance and entries.</p>}<Action onClick={() => setEntry({ goal, entry: null })}>Record contribution or withdrawal</Action><div className="space-y-3">{goal.entries.map(item => <div key={item.id} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border p-3"><div><p className="text-sm">{item.date} · {item.allocationRef} · {item.type} · {formatMoney(item.amountMinor, goal.currency)}</p>{item.note && <p className="mt-1 text-sm text-muted-foreground">{item.note}</p>}</div><div className="flex gap-2"><Action aria-label={`Edit entry ${item.date}`} onClick={() => setEntry({ goal, entry: item })}><Pencil size={15} /></Action><Action aria-label={`Delete entry ${item.date}`} onClick={() => setRemove({ title: "Remove this entry? The allocated balance will be recalculated; no money moves.", command: { type: "delete-entry", goalId: goal.id, id: item.id } })}><Trash2 size={15} /></Action></div></div>)}</div></Panel>)}
    <Panel className="space-y-2"><h3 className="font-semibold">Existing money tools</h3><p className="text-sm text-muted-foreground">New Finance records retain explicit currencies; older unassigned currencies are never guessed. No cross-tool amount is inferred. Holdings and dated market values stay separate from contributions.</p><div className="flex flex-wrap gap-4"><Link href="/account/finance" className="inline-flex min-h-11 items-center text-primary-plus underline">Open Finance</Link><Link href="/account/investments" className="inline-flex min-h-11 items-center text-primary-plus underline">Open Investments</Link></div></Panel>
  </Sheet>{editor && <GoalEditor key={editor.id} initial={editor} busy={busy} onSave={onSave} onClose={() => setEditor(null)} />}{entry && <EntryEditor key={entry.entry?.id ?? entry.goal.id} goal={entry.goal} entry={entry.entry} today={today} busy={busy} onSave={onSave} onClose={() => setEntry(null)} />}{remove && <Confirm title="Confirm removal" description={remove.title} onClose={() => setRemove(null)} onConfirm={async () => { if (!await onSave(remove.command)) throw new Error("Save failed — retry from Momentum."); }} />}</>;
}
