"use client";
import { useAccountCalendar } from "@/hooks/use-account-calendar";
import { useEffect, useState } from "react";
import Link from "next/link";
import {useSearchParams} from "next/navigation";
import { getMomentumSummary } from "@/lib/actions/momentum.actions";
import { dateLabel } from "@/lib/gym/dates";
import type { MomentumData, Review, Summary } from "@/lib/momentum/types";
import type { MomentumCommand } from "@/lib/momentum/validation";
import WeekNavigator from "../gym/WeekNavigator";
import { Action, Field, Panel, Picker, Empty } from "./MomentumUI";
import FocusPanel from "./FocusPanel";
import { focusDuration } from "@/lib/momentum/format";
import type { Activity, Focus } from "@/lib/momentum/types";
import { formatMoney } from "@/lib/momentum/logic";
import { trackerFor } from "@/lib/momentum/goals/evaluate";
import AppLoading from "@/app/components/shared/AppLoading";
function SummaryView({ value, detailed, data }: { value: Summary; detailed: boolean; data: MomentumData }) {
  return <Panel label="Recorded week" className="space-y-4"><h3 className="font-semibold">What is recorded</h3><div className="grid gap-3 sm:grid-cols-3"><div><p className="text-2xl font-semibold text-primary-minus">{value.workouts}</p><p className="text-sm text-muted-foreground">Completed workouts</p><p className="mt-1 text-xs text-muted-foreground">{value.activeWorkouts} active · {value.plannedWorkouts} planned · {value.restDays} rest days</p></div><div><p className="text-2xl font-semibold text-primary-minus">{value.tasks}</p><p className="text-sm text-muted-foreground">Tasks with a completion date</p><p className="mt-1 text-xs text-muted-foreground">{focusDuration(value.focusSeconds)} of logged focus</p></div><div><p className="text-2xl font-semibold text-primary-minus">{value.events}</p><p className="text-sm text-muted-foreground">Confirmed events</p><p className="mt-1 text-xs text-muted-foreground">{value.plannedEvents} planned · {value.adjustments} deliberate adjustments</p></div></div>
    {value.undatedTasks > 0 && <p className="text-xs text-muted-foreground">{value.undatedTasks} older completed tasks have no completion date and are excluded from this week.</p>}{value.scheduledDateEvents > 0 && <p className="text-xs text-muted-foreground">{value.scheduledDateEvents} confirmed events use their scheduled date because no actual completion timestamp was recorded.</p>}
    {detailed && <div className="space-y-2 border-t pt-3 text-sm"><p>{value.strengthSets} actual strength sets</p>{Object.entries(value.cardio).map(([activity, record]) => <p key={activity}>{activity}: {Math.round(record.seconds / 60)} min · {record.knownDistances ? `${record.distanceKm.toFixed(2)} km recorded` : "distance unknown"}</p>)}<p className="text-xs text-muted-foreground">Activity types stay separate. Workouts completed without details contribute no invented sets or cardio metrics.</p></div>}
    <p className="text-xs text-muted-foreground">Missing records do not mean nothing happened. Snapshot as of {new Date(value.asOf).toLocaleString()}.</p>
    {!!value.goalResults?.length && <div className="space-y-3 border-t pt-3"><h4 className="font-medium">Goal Tracker · each goal&apos;s own window</h4>{value.goalResults.filter(item => data.preferences.money || !item.currency).map(item => <div key={item.goalId} className="space-y-1 text-sm"><p>{trackerFor(data).goals.find(goal => goal.id === item.goalId)?.name ?? "Removed goal"} · {item.period}</p><p>{item.currency && trackerFor(data).hideAmounts ? "••••" : item.value === null ? "Needs update" : item.currency ? `${formatMoney(item.value, item.currency)} / ${formatMoney(item.target, item.currency)}` : `${Number(item.value.toFixed(2))} / ${item.target} ${item.metric === "minutes" ? "min" : item.metric === "training-days" ? "training days" : "count"}`} · {item.status}</p><p className="text-xs text-muted-foreground">Rule revision {item.version} · {item.asOf ?? "No dated records"}{item.revised ? " · Revised source result" : ""}. This saved summary stays unchanged until you explicitly refresh it.</p></div>)}</div>}
  </Panel>;
}
function ReviewForm({ week, existing, data, live, busy, onSave, onChoose, onRefresh }: { week: string; existing: Review | undefined; data: MomentumData; live: Summary; busy: boolean; onSave: (command: MomentumCommand) => Promise<boolean>; onChoose: () => void; onRefresh: () => void }) {
  const [worthwhile, setWorthwhile] = useState(existing?.worthwhile ?? ""), [obstacle, setObstacle] = useState(existing?.obstacle ?? ""), [change, setChange] = useState(existing?.change ?? ""), [manageable, setManageable] = useState<string>(existing?.manageable ?? ""), [refresh, setRefresh] = useState(!existing), [id] = useState(existing?.id ?? crypto.randomUUID());
  const save = async (draft: boolean) => { const ok = await onSave({ type: "review", id, week, worthwhile, obstacle, change, manageable: manageable as Review["manageable"], draft, refreshSummary: refresh }); if (ok) setRefresh(false); return ok; };
  return <div className="space-y-5"><SummaryView value={existing && !refresh ? existing.summary : live} detailed={data.preferences.statistics} data={data} />{existing && <div className="space-y-2"><p className="text-sm text-muted-foreground">{existing.draft ? "Saved draft" : "Saved review"} · summary version {existing.version}. Source changes never rewrite your reflections.</p><Action aria-pressed={refresh} onClick={() => { if (!refresh) onRefresh(); setRefresh(!refresh); }}>{refresh ? "Keep saved summary" : "Preview a refreshed summary"}</Action><p className="text-xs text-muted-foreground">Save to retain the refreshed summary as a new version. Your writing stays as entered.</p></div>}
    <Panel className="space-y-5"><h3 className="font-semibold">Three optional questions</h3><Field label="What was worthwhile?" value={worthwhile} maxLength={3000} onChange={event => setWorthwhile(event.target.value)} placeholder="Something I practiced, created, enjoyed or completed" /><div className="flex flex-wrap gap-2">{["A useful first version", "Time for myself", "Returning to my routine"].map(text => <Action key={text} onClick={() => setWorthwhile(text)}>{text}</Action>)}</div><Field label="What got in the way?" value={obstacle} maxLength={3000} onChange={event => setObstacle(event.target.value)} placeholder="Optional observation" /><Field label="What should change next week?" value={change} maxLength={3000} onChange={event => setChange(event.target.value)} placeholder="One adjustment is enough" /><Picker label="Did the training schedule feel manageable? (optional)" value={manageable || "Not answered"} options={["Not answered", "Manageable", "Needs adjustment", "Not sure"]} onChange={value => setManageable(value === "Not answered" ? "" : value)} /><div className="flex flex-wrap gap-2"><Action disabled={busy} onClick={() => void save(true)}>Save draft</Action><Action tone="orange" disabled={busy} onClick={() => void save(false)}>Save weekly review</Action></div></Panel>
    {data.preferences.money && <Panel className="space-y-2"><h3 className="font-semibold">Money · optional review</h3><p className="text-sm text-muted-foreground">Review actual Finance records for this period. Existing transactions have no currency metadata, so Momentum does not invent a currency or combine them into savings. The savings journal records allocations separately.</p><Link href="/account/finance" className="inline-flex min-h-11 items-center text-primary-plus underline">Open Finance</Link></Panel>}
    <Panel className="space-y-3"><h3 className="font-semibold">One optional next move</h3><p className="text-sm text-muted-foreground">A review does not create commitments. Choose a priority explicitly when you are ready.</p><Action tone="blue" onClick={onChoose}>Choose a priority in Today</Action></Panel>
  </div>;
}
export default function WeeklyReview({ data, activities, today, busy, onSave, onChoose, onComplete }: { data: MomentumData; activities: Activity[]; today: string; busy: boolean; onSave: (command: MomentumCommand) => Promise<boolean>; onChoose: () => void; onComplete: (id: string) => Promise<boolean> }) {
  const requestedWeek=useSearchParams().get("week");
  const { browserTimezone, weekStart, weekDates }=useAccountCalendar();
  const [selected, setSelected] = useState(requestedWeek&&/^\d{4}-\d{2}-\d{2}$/.test(requestedWeek)&&!Number.isNaN(Date.parse(requestedWeek))?requestedWeek:today), [live, setLive] = useState<Summary | null>(null), [error, setError] = useState(""), [retry, setRetry] = useState(0), [focusOpen, setFocusOpen] = useState<string | null>(null);
  const week = weekStart(selected);
  const focusSignature = data.focus.map(item => `${item.id}:${item.confirmedSeconds}:${item.savedAt}`).join("|");
  useEffect(() => { let valid = true; getMomentumSummary({ timezone: browserTimezone(), week }).then(summary => { if (valid) { setLive(summary); setError(""); } }).catch(() => { if (valid) setError("The recorded week could not be loaded. Retry; an empty week has not been assumed."); }); return () => { valid = false; }; }, [week, retry, focusSignature,browserTimezone]);
  const existing = data.reviews.find(item => item.week === week);
  const sessions = data.focus.filter(item => item.status === "saved" && weekDates(week).includes(item.date));
  const session: Focus | undefined = sessions.find(item => item.id === focusOpen);
  return <div className="space-y-6"><h2 className="text-xl font-semibold">A short look back</h2><WeekNavigator selected={selected} today={today} showDays={false} onSelect={date => { if (weekStart(date) !== week) { setLive(null); setError(""); setFocusOpen(null); } setSelected(date); }} /><p className="text-sm text-muted-foreground">Week of {dateLabel(week)} · recorded activity, not a score.</p>{error ? <div role="alert" className="space-y-3"><Empty>{error}</Empty><Action onClick={() => { setError(""); setRetry(retry + 1); }}>Retry week</Action></div> : null}{!live && !error ? <AppLoading label="Loading weekly review…" /> : live ? <ReviewForm key={week} week={week} existing={existing} data={data} live={live} busy={busy} onSave={onSave} onChoose={onChoose} onRefresh={() => setRetry(retry + 1)} /> : null}
    {!!sessions.length && <Panel className="space-y-3"><h3 className="font-semibold">Saved focus logs</h3><p className="text-xs text-muted-foreground">Focus logs support an action; they are not additional completed tasks. Open a log to correct its duration or note.</p>{sessions.map(item => <Action key={item.id} onClick={() => setFocusOpen(focusOpen === item.id ? null : item.id)}>{item.date} · {focusDuration(item.confirmedSeconds ?? 0)} logged · {focusOpen === item.id ? "Hide log" : "Review log"}</Action>)}{session && <FocusPanel key={`${session.id}:${session.savedAt}`} focus={session} activities={activities} busy={busy} onSave={onSave} onComplete={onComplete} />}</Panel>}
  </div>;
}
