"use client";
import Link from "next/link";
import { Check, ArrowUpRight } from "lucide-react";
import { Button } from "@/app/components/ui/button";
import { annualAmount } from "@/lib/landing/offer";
import { useLanding, MainAction } from "./LandingProvider";
export default function AnnualMembership(){
 const {currency,paid,trialDays,availability}=useLanding();
 return <section id="membership" className="mf-section mf-membership" aria-labelledby="membership-heading"><div><p className="mf-eyebrow">A little structure. All year.</p><h2 id="membership-heading">One membership.<br/>Your whole <span>system.</span></h2><p>Start with a no-card trial.<br/>Choose the annual membership when you&apos;re ready.</p><p className="mf-small mt-6">Fixed annual prices, separate from your Finance currencies and investment records. No exchange-rate conversion.</p></div><div className="mf-price-card"><p className="mf-eyebrow">ManForth Annual Membership</p><div className="mf-price"><strong>{annualAmount(currency)}</strong><span>{currency} / year</span></div><p className="mf-small">Full yearly amount. Configured applicable tax included.</p><p className="mf-price-location">{paid?"Your current subscription's recorded currency.":"Selected automatically for your region. Checkout charges this currency."}</p><ul className="mf-inclusions">{["Finance & Investments","To-Do & weekly Events","Gym planner & training log","Momentum goals & Journeys"].map(text=><li key={text}><Check size={17}/>{text}</li>)}</ul><MainAction/><p className="mf-trial-line">{trialDays}-day trial · No card required</p><p className="mf-small">No card required for the trial. Choose annual membership to continue. Billed annually. Renews annually unless canceled.</p><p className="mf-small mt-3">Purchasing during a trial charges now and begins your paid year.</p><Button asChild variant="outline" className="mf-confirm-price"><Link prefetch={false} href="/account?section=membership">Review membership & confirm price<ArrowUpRight size={15}/></Link></Button><p className="mf-availability" role="status">{availability[currency]===false?`Annual purchase in ${currency} is currently unavailable. The no-card trial does not need billing configuration.`:availability[currency]===true?"Final price confirmation and secure checkout are in Account & Settings.":"Purchase availability is confirmed in Account & Settings."}</p></div></section>;
}
