// Review content shared by the server-only repository and the operator CLI.
// No authentication, database handle or provider secrets belong in this module.
import { annualPrices, launchPolicy } from "../account/config";
import { brand } from "../brand";
import type { LegalDocument, LegalKind } from "./types";

/** Editable review text only. Publication stores a frozen, independently approved copy. */
export function draftDocuments(): Record<LegalKind, LegalDocument> {
  const fact = (key: string) => process.env[key]?.trim() || `[REVIEW REQUIRED: ${key}]`;
  const operator = { name: fact("LEGAL_OPERATOR_NAME"), form: fact("LEGAL_OPERATOR_FORM"), country: fact("LEGAL_OPERATOR_COUNTRY"), address: fact("LEGAL_OPERATOR_ADDRESS"), registration: fact("LEGAL_OPERATOR_REGISTRATION"), tax: fact("LEGAL_OPERATOR_TAX"), contact: process.env.LEGAL_CONTACT_EMAIL?.trim() || brand.supportEmail };
  const base = (kind: LegalKind, title: string, introduction: string): LegalDocument => ({ id: `b1-way-personal:${kind}:en:2026-10-03-draft.1`, product: "b1-way-personal", locale: "en", kind, version: "2026-10-03-draft.1", title, introduction, effectiveDate: "2026-10-03", updatedAt: "2026-10-03", operator, sections: [] });
  const terms = base("terms", "Terms & Conditions — ManForth by B1-Way", "These terms explain the ManForth web service, your account and the separate choice to purchase membership. Read them together with the Privacy Policy. Mandatory consumer protections continue to apply.");
  terms.offer = { annualPrices: { ...annualPrices }, trialDays: launchPolicy().trialDays, currencyPolicy: "New purchases: PL → PLN, GB → GBP, US → USD; other or unknown regions → EUR. Existing subscriptions retain their recorded currency." };
  terms.sections = [
    { id: "operator", title: "1. Who provides this service", paragraphs: [`ManForth is the personal-development product branded by B1-Way. The contracting operator is ${operator.name}, ${operator.form}, established in ${operator.country}, at ${operator.address}. Registration: ${operator.registration}. Tax/VAT: ${operator.tax}. Contact: ${operator.contact}. A brand, domain or billing currency does not establish our legal entity.`, "These terms concern ManForth only. The separate B1-Way language-learning product has separate plans and policies; a ManForth membership does not include its subscription.", "[REVIEW REQUIRED: confirm operator, intended markets, contract language, governing law and rights-preserving jurisdiction/dispute-resolution information. Do not impose an exclusive foreign forum on consumers.]" ] },
    { id: "accounts", title: "2. Account creation and eligibility", paragraphs: ["Verify your email through the registration flow and choose a display name and password. We record your affirmative acceptance of these Terms and acknowledgment that the Privacy Policy was provided. This is separate from optional consent, cookies and payments. Keep your credentials secure and your necessary account information accurate. Contact support if you suspect misuse.", "[REVIEW REQUIRED: confirm the intended adult-only product rule and any separate eligibility confirmation. The inspected signup has no age checkbox; do not claim an existing age check or collect identity documents/date of birth without a reviewed necessity.]", "New account creation is blocked until approved policies are published. Existing customers retain security, billing management, support, export and deletion controls. We do not invent historical acceptance for existing accounts."] },
    { id: "service", title: "3. The service and your records", paragraphs: ["ManForth offers expense/revenue records, manually added investment positions, To-Do boards, weekly Events, workout templates/plans/actual logs and Momentum goals, focus records, Journeys and reviews. Planning and confirmation are different: a target or scheduled item is not evidence that it happened.", "A supported modern browser and internet access are needed for account synchronization. Device-local display ordering and interface preferences may differ between browsers. A failed save or unavailable connection is not a confirmed server save. No uninterrupted uptime or full offline synchronization is promised.", "You retain rights in your content. You grant only the permission needed to store, process, display and export that content to operate the service for you. This does not authorize selling private records, publishing them or using them to train AI."] },
    { id: "use", title: "4. Reasonable use and service security", paragraphs: ["Do not misuse another person's account, interfere with service security, upload unlawful content or attempt to bypass ownership checks and reasonable rate limits. These restrictions do not remove legal exceptions or statutory rights. We may investigate credible abuse and use proportionate protective measures.", "[REVIEW REQUIRED: fair notice, review/appeal and suspension procedures, including urgent security exceptions. Paid-through rights and available remedies must be addressed before terminating access.]" ] },
    { id: "tracking", title: "5. Training, money and progress", paragraphs: ["Gym presets and exercise information support planning and logging. Ask a qualified trainer to check suitability and technique; seek appropriate professional advice for health conditions or injuries. Do not enter diagnoses or medical history unnecessarily. We do not diagnose, guarantee transformations or automatically prescribe heavier weights.", "Finance and Investments record information you supply and available market quotes. They are not banking, brokerage or individualized investment, tax or legal advice. They do not move money, buy assets or guarantee returns. Quotes can be delayed or unavailable. Investments use USD; Finance records retain their recorded currencies.", "Goals and focus totals reflect recorded inputs and chosen rules, not proof of mastery, income growth or achievement. Web walking-step collection is not implemented in this build. We do not claim automatic all-day steps, GPS or native health access.", "These limitations do not waive liability or mandatory remedies for failures in our own service."] },
    { id: "membership", title: "6. Trial and annual membership", paragraphs: [`The configured no-card trial is ${terms.offer.trialDays} days and starts only when an eligible verified user explicitly starts it in Account & Settings. Registration and email verification neither start the trial nor authorize payment. Only one product trial is available per account under the existing eligibility rules.`, `The annual offer snapshot for this document is ${annualPrices.PLN / 100} PLN, ${annualPrices.GBP / 100} GBP, ${annualPrices.USD / 100} USD or ${annualPrices.EUR / 100} EUR per year. These are fixed regional prices, not exchange-rate conversions. The selected price, currency and material terms must be confirmed before purchase. The displayed price includes configured applicable tax; merchant/tax treatment requires operator review.`, "An elective purchase during a trial charges the full annual amount now and begins the paid year after provider confirmation. It does not defer payment to trial expiry or supply another trial. Purchased annual membership renews unless canceled. Stripe handles payment and provider-confirmed periods determine paid access; a success URL does not grant access.", "Cancellation of renewal preserves confirmed paid access until its end date. Use Account & Settings → Membership & billing → Manage payments, receipts & cancellation. After access expires, saved records remain readable and support, security, billing, export and deletion remain available under the current access policy. Cancellation, statutory withdrawal, refunds/remedies and account deletion are different actions."] },
    { id: "withdrawal", title: "7. Withdrawal and consumer remedies", paragraphs: ["The product trial does not replace statutory withdrawal rights. Registration does not waive withdrawal, authorize immediate paid performance or turn an ongoing digital service into a downloaded file. Any legally required early-start request or acknowledgment must be obtained specifically at the relevant transaction.", `[REVIEW REQUIRED: qualified adviser to determine contract formation and applicable withdrawal periods, exceptions, early-performance conditions, digital-service conformity obligations and national implementation for each intended market. Review the online withdrawal function introduced by Directive (EU) 2023/2673 and current national measures; purchases remain blocked until the necessary process and confirmation delivery are reviewed.]`, `Proposed model notice (not an automatic submission): To ${operator.name}, ${operator.address}, ${operator.contact}: “I hereby give notice that I withdraw from my contract for the provision of ManForth. Ordered on: ____. Consumer name: ____. Consumer address: ____. Date: ____. Signature only if sent on paper.” Send an unambiguous notice using a confirmed contact route. You do not have to use this wording.`, "No ‘all sales final’ rule or blanket loss of mandatory remedies is imposed. There is no simulated withdrawal button; the required operational route/function is a publication and purchase dependency."] },
    { id: "complaints", title: "8. Complaints and support", paragraphs: [`Contact ${operator.contact} about the service, billing questions, complaints or privacy requests. A mailto link opens your email client and is not proof that a request was sent or received. You do not need active membership to contact support.`, "[REVIEW REQUIRED: verify receiving mailbox, geographical request route, complaint deadlines, durable acknowledgment and applicable dispute-resolution information. Do not link obsolete EU ODR services or invent response guarantees.]" ] },
    { id: "changes", title: "9. Changes, suspension and termination", paragraphs: ["Material contract or price changes require a fair reason, appropriate notice, an effective date and any reviewed contractual choice or remedy. Visiting again does not silently bind you to new terms or wider data use. Cosmetic changes should not automatically force reacceptance. Existing accepted versions remain reproducible.", "[REVIEW REQUIRED: operator-approved migration and reacceptance process for existing users and material revisions, including paid access if users decline; do not invent automatic forfeiture. Do not interrupt unsaved training or remove security/cancellation/export/deletion access.]", "Account deletion follows the existing password-confirmed process: pending checkout/renewal obligations are resolved before application records and identity are removed. Deletion does not automatically produce a refund or guarantee instantaneous erasure of every provider record or backup."] },
    { id: "confirmation", title: "10. Contract copies and communications", paragraphs: ["Exact legal versions are retained in the account's agreement evidence and can be downloaded. A changing webpage, read inbox message or Stripe receipt is not by itself treated as every required contractual confirmation.", "[REVIEW REQUIRED: retainable contract/withdrawal confirmation and mandatory-notice delivery mechanism, including purchase details. A user-initiated immutable JSON download is implemented but is not presumed sufficient delivery. No legal emails, marketing campaigns or push notifications are introduced by this update.]" ] },
  ];
  const privacy = base("privacy", "Privacy Policy — ManForth by B1-Way", "This notice explains information used by the ManForth web application. Acknowledging receipt of this policy does not consent to every processing purpose, marketing, payments or future health integrations.");
  privacy.sections = [
    { id: "controller", title: "1. Controller, product and contact", paragraphs: [`The proposed controller is ${operator.name}, ${operator.form}, in ${operator.country}, at ${operator.address}. Registration: ${operator.registration}; tax details: ${operator.tax}. Privacy contact: ${operator.contact}.`, "[REVIEW REQUIRED: verify the controller and any joint-controller relationship. Add DPO/representative information only if appointed/required. Confirm territorial applicability; branding alone does not transfer data between B1-Way products.]" ] },
    { id: "information", title: "2. Information and its sources", paragraphs: ["Required account information includes your display name, email, verification state, protected credential information, sessions and security-related technical records. Passwords are protected through the existing authentication library; plaintext passwords are not stored as profile fields. Password-safety checks send a padded hash prefix to Have I Been Pwned, not your plaintext password.", "Optional module content comes from your entries/imports: tasks and notes; event dates, optional times, presets and completion; workout templates, scheduled targets, actual strength/cardio logs and exercise notes; financial records/categories and USD investment positions; goals, focus records, reflections and reviews. Measurement-unit preferences do not prove body measurements are collected. Manual walking-step tracking is absent in this build.", "Membership identifiers/status and billing details actually received come from verified Stripe provider data and signed webhook events. Authentication delivery status comes from Resend responses/signed delivery events. Legal records store the presented document versions/copies and your explicit Terms acceptance and privacy acknowledgment. Support content is information you choose to send to the operator's confirmed mailbox; no in-app support-ticket backend is assumed.", "[REVIEW REQUIRED: verify the actual technical/log fields and deployed support mailbox/vendor; audit infrastructure logs and any untracked optional health information.]" ] },
    { id: "purposes", title: "3. Purposes and proposed lawful bases", paragraphs: ["Service/account delivery: necessary account and module records, proposed contract/pre-contract basis where processing is objectively necessary to provide the requested service. Optional content is not a license for unrelated processing.", "Security/abuse prevention: session, verification/quota/suppression and technical records, proposed legitimate interest in protecting users and service integrity, subject to a documented necessity/balancing assessment. Do not classify every fraud/analytics purpose as contract necessity.", "Billing and required records: Stripe identifiers, selected offers and legal/purchase evidence, proposed contract basis for purchases and identified legal obligations for records actually required by applicable law. Support: necessary request information under the relevant contract or assessed legitimate interest. Retention of dispute evidence requires a reviewed basis and time/criteria.", "[REVIEW REQUIRED: identify specific statutory obligations, complete the purpose/data/necessity/recipient/retention register and legitimate-interest assessment in docs/legal-readiness.md. No optional analytics or marketing basis is inferred from this acknowledgment.]" ] },
    { id: "health", title: "4. Training and potentially sensitive content", paragraphs: ["Fitness logs, pain-related notes, reflections or other supplied content may reveal health information in context. Financial information is private but is not automatically an Article 9 special category. We do not ask for diagnoses or medical histories for registration.", "[REVIEW REQUIRED: assess actual Gym/reflection processing under Articles 6 and 9 and implement necessary feature-level safeguards/condition before launch. If specific explicit consent is selected, implement a separate informed choice and withdrawal control at that feature. This registration acknowledgment is not that consent. New collection requiring an unresolved basis is blocked for launch.]" ] },
    { id: "recipients", title: "5. Providers and recipients", paragraphs: ["Inspected integrations use Neon/PostgreSQL for account and application storage, Better Auth within our backend for authentication, Resend for verification/recovery/security email and Stripe for payment/customer/renewal processing. Vercel is the configured public deployment target, not evidence of a verified hosting region. Cloudflare Turnstile verifies abuse-prevention challenges on signup and recovery.", "Server-side market lookups use CoinGecko and Yahoo Finance for ticker quotes; reviewed symbol/coin IDs may be sent, without a user's account name or email in those requests. Password breach checks use a padded hash-prefix request to Have I Been Pwned. These flows need appropriate role/region/terms assessment; not every provider acts solely as our processor for every purpose.", "[REVIEW REQUIRED: confirm actual deployed providers, contracts, subprocessors, monitoring, support handling, recipient roles and regions. No unverified vendor list or claim of ‘nothing shared’ is made.]" ] },
    { id: "transfers", title: "6. International processing", paragraphs: ["[REVIEW REQUIRED: identify actual processing locations, transfer mechanisms and access to relevant safeguards for each recipient. Do not assume all data stays in the EU, that a DPA/SCC is signed, or that an adequacy decision covers every flow. Supply a confirmed request route for safeguard information before publication.]" ] },
    { id: "retention", title: "7. Retention and deletion", paragraphs: ["Verification codes expire after 10 minutes; signup sends and attempts have server-enforced daily limits. Expired/failed/sent email payloads are cleared by the worker. This update clears unfinalized legal/signup evidence after the verification attempt has expired plus a 24-hour retry boundary; this does not establish a universal retention rule for all email logs.", "Application content remains associated with the account until removed through the relevant module or the account-deletion process. Legal acceptance/purchase evidence is owned and deleted with the account under the current implementation; any mandatory retention exception must be decided and implemented before publication/purchases. Deletion waits for safe billing resolution. Provider financial records, operational tombstones and backups may need different treatment.", "[REVIEW REQUIRED: approve category-specific retention for security/rate logs, email metadata/suppression, pending signup, content, support, legal/billing evidence, deletions and backups; verify jobs, restore rehearsals and legal holds. No instant erasure from every backup/Stripe system or indefinite evidence retention is promised.]" ] },
    { id: "security", title: "8. Security measures", paragraphs: ["Implemented safeguards include authenticated ownership checks, protected passwords, server-side validation and rate limits, timestamped single-use email proof, encrypted queued mail and signed provider webhooks. Access credentials and provider secrets are not included in account exports. Production transport/access/backup controls require deployment verification. These measures do not promise perfect security or end-to-end encryption."] },
    { id: "rights", title: "9. Your rights and requests", paragraphs: [`Where applicable you may request access, correction, erasure, restriction, portability or object to relevant processing. Consent-based purposes, if separately introduced, must provide withdrawal without affecting previous lawful processing. Contact ${operator.contact}; Account & Settings → Privacy & Legal provides export and password-confirmed deletion even after membership expires. There is no blanket ‘withdraw privacy policy acceptance’ switch.`, "Under the GDPR requests generally require a response within one month, subject to the applicable conditions/extensions and identity checks. A deletion request may have lawful limitations which must be explained. You may complain to a competent supervisory authority, including in your habitual residence, workplace or place of an alleged infringement where applicable. UODO is relevant where Polish jurisdiction applies; users are not restricted to that authority.", "[REVIEW REQUIRED: confirm the request process, controller-specific authority/contact, deadlines and any lawful retention exception. No active payment is required to exercise rights.]" ] },
    { id: "storage", title: "10. Cookies, storage and regional pricing", paragraphs: ["Necessary authentication/session and HttpOnly email-proof cookies support login and verification. Interface theme/sidebar state, device-local Finance ordering and Momentum change signals may use browser storage. These are separate from registration agreement. Local public demo state is not private account data. No advertising/analytics SDK was found in the inspected app source; production tags and hosting analytics remain to be audited.", "Cloudflare's abuse-prevention script runs on applicable identity forms; policies themselves do not load it. Audit necessity and provider storage before publication. Do not add a misleading optional ‘Accept all’ banner when no such choices exist.", "For a new membership offer, trusted coarse country information from the hosting request can select the fixed billing currency. It is not GPS, proof of residence or applicable law. Unknown/untrusted countries fall back to EUR. The app does not persist country for this pricing lookup; hosting/network providers may process IP/technical data under their own applicable arrangements.", "[REVIEW REQUIRED: verify a real browser/infrastructure storage inventory, lifetimes, bot-protection treatment, consent requirements and deployed scripts. Nonessential tracking must remain off absent an appropriate reviewed choice.]" ] },
    { id: "communications", title: "11. Notifications and product boundaries", paragraphs: ["Product reminders remain inside the app. This update retires optional reminder-email dispatch and hides legacy email/marketing toggles without treating old preferences as registration consent. Authentication verification/recovery and existing security notices remain separate. There are no new campaigns, legal-email sends or browser/native push permissions.", "This web build does not collect native health permissions, profile-photo uploads, precise GPS, automatic phone/watch steps or bank/broker connections. An account's old optional records can exist and are not invented by this policy. A future integration needs review and appropriate information/choices before collection begins."] },
    { id: "automation", title: "12. Calculations, suggestions and updates", paragraphs: ["Recorded goals, focus totals, workout comparisons and regional pricing use rule-based processing. Security controls can block abusive requests. Exercise suggestions do not diagnose or create a legally binding treatment decision. We have not assumed that no automated decision can ever be legally significant; deployment/use context requires review.", "Published versions are available for reference. Material changes require appropriate transparency; a new consent-based purpose needs its own choice. Reading an inbox message is not contract acceptance. Native health, push and app-store agreements are outside this web registration acknowledgment.", "[REVIEW REQUIRED: assess Article 22 relevance, notice procedures and future changes. Effective/updated dates belong to the frozen document version, not every deployment.]" ] },
  ];
  return { terms, privacy };
}
export function allowDraftPreview() {
  if (process.env.VERCEL_ENV === "production") return false;
  if(process.env.NODE_ENV !== "production") return true;
  try{return process.env.LEGAL_DRAFT_PREVIEW === "true" && new URL(process.env.APP_URL || "http://localhost:3000").hostname === "localhost";}catch{return false;}
}
