"use client";
import { useEffect, useState } from "react";
import { Trash2 } from "lucide-react";
import { getNamedWeekPresets, saveNamedWeekPreset, removeNamedWeekPreset, type NamedWeekPreset } from "@/lib/actions/planner.actions";
import type { EventItems } from "@/types/types";
import { Confirm, Field, GymButton, GymDialog } from "../gym/GymUI";
export default function WeekPresets({ mode, week, board, onApply, onClose }: { mode: "save" | "apply"; week: string; board: EventItems[]; onApply: (board: EventItems[]) => void; onClose: () => void }) {
  const [items, setItems] = useState<NamedWeekPreset[] | null>(null), [error, setError] = useState(""), [busy, setBusy] = useState(false), [reload, setReload] = useState(0), [id, setId] = useState(() => crypto.randomUUID()), [name, setName] = useState(""), [preview, setPreview] = useState(false), [remove, setRemove] = useState<NamedWeekPreset | null>(null);
  useEffect(() => { let valid = true; getNamedWeekPresets().then(value => { if (valid) { setItems(value); setError(""); } }).catch(() => { if (valid) setError("Presets could not be loaded. Retry; nothing has been replaced."); }); return () => { valid = false; }; }, [reload]);
  const existing = items?.find(item => item.id === id);
  return <><GymDialog open title={mode === "save" ? "Save a named week preset" : "Your week presets"} description="Keep up to three reusable weeks. Applying creates fresh plans, never completed results." onClose={() => { if (!busy) onClose(); }}>
    {!items && !error && <p role="status">Loading presets…</p>}{items && <div className="space-y-3"><p className="text-sm text-muted-foreground">{items.length} / 3 saved</p>{items.map(item => <div key={item.id} className="flex items-center gap-2 rounded-2xl border p-3"><GymButton className="flex-1 justify-start" tone={item.id === id ? "blue" : "neutral"} disabled={busy} onClick={() => { if (mode === "apply") onApply(item.board as EventItems[]); else { setId(item.id); setName(item.name); setPreview(false); } }}>{item.name} · {item.board.reduce((sum, day) => sum + day.tasks.length, 0)} plans</GymButton><GymButton aria-label={`Remove week preset ${item.name}`} disabled={busy} onClick={() => setRemove(item)}><Trash2 size={16} /></GymButton></div>)}{!items.length && mode === "apply" && <p>No saved weeks yet. Save a week to reuse its plans.</p>}
    {mode === "save" && <form className="space-y-4" onSubmit={async event => { event.preventDefault(); if (!preview) { setPreview(true); return; } setBusy(true); setError(""); try { const result = await saveNamedWeekPreset({ id, name, week, board, before: items }); if (!result.success) throw new Error(result.message); onClose(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Save failed — retry"); } finally { setBusy(false); } }}>
      {items.length < 3 && <GymButton disabled={busy} onClick={() => { setId(crypto.randomUUID()); setName(""); setPreview(false); }}>New preset</GymButton>}<Field label="Preset name" required maxLength={80} disabled={busy} value={name} onChange={event => { setName(event.target.value); setPreview(false); }} />
      {preview && <p className="rounded-2xl border p-3 text-sm">{existing ? `Replace “${existing.name}” with the selected week's plans?` : `Save “${name}” as a new preset?`} Completed states, timestamps and actual workout results are excluded. Scheduled weeks remain unchanged.</p>}
      <GymButton type="submit" tone="blue" disabled={busy || (items.length === 3 && !existing)}>{busy ? "Saving…" : preview ? existing ? "Confirm replacement" : "Save preset" : "Preview preset"}</GymButton>{items.length === 3 && !existing && <p>Select a saved preset to replace it.</p>}
    </form>}</div>}{error && <div role="alert" className="space-y-2"><p>{error}</p><GymButton disabled={busy} onClick={() => setReload(reload + 1)}>Reload presets</GymButton></div>}
  </GymDialog>{remove && <Confirm title={`Remove ${remove.name}?`} description="Removes only this reusable preset. Scheduled events and workouts remain unchanged." onClose={() => setRemove(null)} onConfirm={async () => { if (!items) return; const result = await removeNamedWeekPreset({ id: remove.id, before: items }); if (!result.success) throw new Error(result.message); setItems(result.data); }} />}</>;
}
