import test from 'node:test';
import assert from 'node:assert/strict';
import {loadModule, plain} from './helpers.mjs';
import {fixture,blueprint,dates,events,logic as gymLogic} from './gym-fixture.mjs';
import {types,goalTypes,logic,goalEvaluation,emptySources} from './momentum-fixture.mjs';

// Real action/domain code; the Drizzle adapter and post-commit inbox hook are isolated.
// This checks the connected contract, not PostgreSQL transactions or browser dragging.
test('saved planned workout → actual results → one Event and Momentum count → inbox; correction withdraws completion',async()=>{
  const now='2026-10-03T15:00:00.000Z',date='2026-10-03',zone='Europe/Warsaw';
  const state=fixture({now}),bp=blueprint(['bench-press','stationary-cycling']);
  bp.exercises[0].targets.loadKg=60;
  const schedule={operationId:crypto.randomUUID(),dates:[date],timezone:zone,data:bp};
  const planned=await state.actions.scheduleGymWorkout(schedule); assert.equal(planned.success,true);
  await state.actions.scheduleGymWorkout(schedule); assert.equal(state.rows.gymPlans.length,1);
  const plan=planned.plans[0], id=crypto.randomUUID();
  const started=await state.actions.startGymSession({id,planId:plan.id,data:null,date,timezone:zone,logged:true});
  assert.equal(started.success,true);
  let record=started.session;
  assert.equal(record.data.exercises[0].sets.every(set=>set.loadKg===null&&!set.completed),true);
  let draft=structuredClone(record.data);
  Object.assign(draft.exercises[0].sets[0],{loadKg:60,reps:10});
  Object.assign(draft.exercises[0].sets[1],{loadKg:55,reps:9});
  Object.assign(draft.exercises[1].cardio,{seconds:1500,distanceKm:8.4});
  draft=gymLogic.confirmSessionEntries(draft);
  const write={id,revision:record.revision,mutationId:crypto.randomUUID(),data:draft};
  const saved=await state.actions.saveGymSession(write); assert.equal(saved.success,true);
  assert.equal((await state.actions.saveGymSession(write)).session.revision,saved.session.revision);
  record=(await state.actions.getGymData()).sessions[0];
  assert.equal(record.data.exercises[0].sets[1].loadKg,55);assert.equal(record.data.originalPlan.exercises[0].targets.loadKg,60);
  const done=await state.actions.completeGymWorkout({id,sessionId:id,planId:plan.id,revision:record.revision,mutationId:crypto.randomUUID(),date,timezone:zone,notes:''});
  assert.equal(done.success,true);
  assert.equal(done.session.data.finishedAt,now);
  assert.equal(state.rows.gymSessions.length,1);
  const sources=emptySources();sources.gym=await state.actions.getGymData();
  const momentum=types.emptyMomentum(),goal={id:crypto.randomUUID(),name:'Three workouts',lifecycle:'active',hidden:false,pinned:false,order:0,createdAt:now,updatedAt:now,reminder:{enabled:false,days:[6],time:'09:00',leadDays:null},versions:[{revision:1,effectiveFrom:'2026-10-01',rule:{metric:'sessions',target:3,currency:null,period:'weekly',start:'2026-10-01',end:null,timezone:zone,scopeId:null,sources:[],journeyId:null,throughout:false,freshnessDays:7}}]};
  momentum.tracker={...goalTypes.emptyTracker(),goals:[goal]};
  const evaluate=()=>goalEvaluation.evaluateGoal(goal,momentum,{...sources,activities:logic.sourceActivities(sources,zone)},now);
  const producer=loadModule('lib/notifications/produce.ts',{'../gym/dates':dates,'../events':events,'../momentum/logic':logic,'../momentum/goals/evaluate':goalEvaluation});
  const prefs=loadModule('lib/account/preferences.ts');
  const messages=()=>producer.produceMessages({sources,momentum,preferences:prefs.defaultPreferences,notifications:{...prefs.defaultNotifications,quietHours:false},initializedAt:'2026-10-02T00:00:00Z',first:false,known:new Set(),now});
  const project=()=>events.plannerItems([],sources.gym,date);
  let items=project();assert.equal(items.length,1);assert.equal(items[0].session.id,id);assert.equal(items[0].plan.id,plan.id);assert.equal(items[0].completed,true);
  let summary=logic.buildSummary(sources,logic.sourceActivities(sources,zone),momentum,dates.weekStart(date),zone,now);
  assert.equal(summary.workouts,1);assert.equal(summary.strengthSets,2);assert.equal(summary.cardio['Stationary cycling'].seconds,1500);
  assert.equal(summary.cardio['Stationary cycling'].distanceKm,8.4);assert.equal(evaluate().value,1);
  assert.equal(messages().filter(message=>message.category==='workout_completed').length,1);
  const reopen={id,revision:done.session.revision,mutationId:crypto.randomUUID()};
  const reopened=await state.actions.reopenGymWorkout(reopen);assert.equal(reopened.success,true);assert.equal((await state.actions.reopenGymWorkout(reopen)).session.revision,reopened.session.revision);
  sources.gym=await state.actions.getGymData();
  assert.equal(project().length,1);assert.equal(project()[0].completed,false);assert.equal(evaluate().value,0);
  assert.equal(messages().filter(message=>message.category==='workout_completed').length,0);
  assert.deepEqual(plain(reopened.session.data.exercises),plain(done.session.data.exercises));
  const correction=structuredClone(reopened.session.data);correction.date='2026-10-02';correction.exercises[0].sets[1].reps=8;
  const corrected=await state.actions.saveGymSession({id,revision:reopened.session.revision,mutationId:crypto.randomUUID(),data:correction});assert.equal(corrected.success,true);
  const finished=await state.actions.completeGymWorkout({id,sessionId:id,planId:plan.id,revision:corrected.session.revision,mutationId:crypto.randomUUID(),date:correction.date,timezone:zone,notes:''});assert.equal(finished.success,true);
  sources.gym=await state.actions.getGymData();assert.equal(project()[0].date,'2026-10-02');assert.equal(evaluate().value,1);
  assert.equal(messages().filter(message=>message.category==='workout_completed').length,1);
  assert.equal(sources.gym.sessions[0].data.originalPlan.exercises[0].targets.reps,10);
  assert.equal(sources.gym.sessions[0].data.exercises[0].sets[1].reps,8);
  const copied=await state.actions.copyGymWeek({operationId:crypto.randomUUID(),from:date,to:'2026-10-12',timezone:zone});assert.equal(copied.success,true);
  assert.equal(copied.plans.length,1);assert.notEqual(copied.plans[0].id,plan.id);assert.equal(state.rows.gymSessions.length,1);
});
