import test from 'node:test';import assert from 'node:assert/strict';import {loadModule} from './helpers.mjs';
class MobileError extends Error{constructor(status,code,message){super(message);this.status=status;this.code=code;}}
const success=value=>({ok:true,value});
function adapter({pending=null,proof={owner_id:'a',purpose:'verify-account',email:'a@example.invalid',consumed_at:null},user={email:'a@example.invalid',email_verified:true},deletionResult={ok:false,error:'Deletion is pending.'}}={}){
 const calls=[],jar=new Map();const sql=async parts=>parts.join('').includes('b1_deletions')?pending?[pending]:[]:[user];
 const accountModule=loadModule('lib/mobile/account.ts',{'next/headers':{cookies:async()=>({get:k=>jar.has(k)?{value:jar.get(k)}:undefined,set:(k,v)=>jar.set(k,v),delete:k=>jar.delete(k)})},'../account/store':{accountSql:sql},'../account/email/crypto':{attemptToken:()=> 'x'.repeat(64),protectedKey:s=>s},'../account/email/challenges':{challengeState:async()=>proof},'../actions/identity.actions':{accountSessions:async()=>success([]),revokeAccountSession:async id=>{calls.push(id);return success({message:'Session signed out'});},confirmEmailCode:async()=>{calls.push('code');return success({verified:true});},completeAccountEmail:async()=>{calls.push('complete');return success({email:user.email});}},'../actions/account.actions':{saveAccountName:async()=>{calls.push('name');return {name:'Valid'};}},'../actions/privacy.actions':{deletePersonalAccount:async()=>deletionResult,exportAccountData:async()=>success({owned:true})},'./http':{MobileError}});
 return {...accountModule,calls};
}
test('mailbox capability binding rejects another owner before code verification or consumption',async()=>{const a=adapter();await assert.rejects(a.writeMobileAccount('b',{type:'proof-confirm',proof:'x'.repeat(64),code:'123456'}),e=>e.status===403);assert.deepEqual(a.calls,[]);});
test('repeated consumed proof only acknowledges actual verified current mailbox and never repeats identity mutation',async()=>{const a=adapter({proof:{owner_id:'a',purpose:'verify-account',email:'a@example.invalid',consumed_at:'2026-10-04T12:00:00Z'}});assert.equal((await a.writeMobileAccount('a',{type:'proof-confirm',proof:'x'.repeat(64),code:'123456'})).email,'a@example.invalid');assert.deepEqual(a.calls,[]);const b=adapter({proof:{owner_id:'a',purpose:'verify-account',email:'old@example.invalid',consumed_at:'2026-10-04T12:00:00Z'}});await assert.rejects(b.writeMobileAccount('a',{type:'proof-confirm',proof:'x'.repeat(64),code:'123456'}));});
test('pending deletion is returned as pending despite failed provider; profile is locked but sessions remain accessible',async()=>{const pending={status:'retry',created_at:'2026-10-04T12:00:00Z',completed_at:null},a=adapter({pending});const result=await a.writeMobileAccount('a',{type:'delete',password:'p',confirmation:'DELETE MY ACCOUNT',stopRenewals:true});assert.equal(result.signInRequired,false);assert.equal(result.deletion.status,'retry');await assert.rejects(a.writeMobileAccount('a',{type:'name',name:'Valid'}),e=>e.code==='deletion');assert.equal((await a.writeMobileAccount('a',{type:'revoke-session',id:'owned-session'})).message,'Session signed out');});
test('only a completed durable tombstone reports account removal; unknown outcome remains an error',async()=>{const a=adapter({pending:{status:'completed',created_at:'2026-10-04T12:00:00Z',completed_at:'2026-10-04T12:01:00Z'}});assert.equal((await a.writeMobileAccount('a',{type:'delete',password:'p',confirmation:'DELETE MY ACCOUNT',stopRenewals:true})).signInRequired,true);await assert.rejects(adapter().writeMobileAccount('a',{type:'delete',password:'p',confirmation:'DELETE MY ACCOUNT',stopRenewals:true}));});
test('QA mail adapter rejects production, administrator credentials and mismatched actual database identity',async()=>{const env={NODE_ENV:'development',MANFORTH_MOBILE_QA_LOCAL:'true',MANFORTH_MOBILE_QA_MAIL:'true',DATABASE_URL:'postgres://manforth_mobile_qa:ignored@qa.neon.tech/qa_tablename'};
 for(const change of [{NODE_ENV:'production'},{RESEND_API_KEY:'re_live_never_use'},{DATABASE_URL:'postgres://admin:ignored@qa.neon.tech/qa_tablename'},{DATABASE_URL:'postgres://manforth_mobile_qa:ignored@qa.neon.tech/application'}])assert.throws(()=>loadModule('lib/account/email/qa-adapter.ts',{'../store':{}},{process:{env:{...env,...change}}}).qaMailEnabled());
 const a=loadModule('lib/account/email/qa-adapter.ts',{'../store':{accountSql:async()=>[{database:'application',role:'manforth_mobile_qa'}]}},{process:{env}});assert.equal(a.qaMailEnabled(),true);await assert.rejects(a.verifyQaMail());
});
test('isolated mail retains pending encrypted outbox and cannot fabricate provider delivery',async()=>{let checked=0;const delivery=loadModule('lib/account/email/delivery.ts',{resend:{Resend:class{constructor(){throw Error('Provider construction forbidden');}}},'../store':{},'../config':{},'./crypto':{},'./policy':{},'./qa-adapter':{qaMailEnabled:()=>true,verifyQaMail:async()=>{checked++;}}});assert.equal((await delivery.processMailQueue()).length,0);assert.equal(checked,1);await assert.rejects(delivery.resendClient().emails.send({}));});

function identityActions(){let removed=0;const auth={api:{getSession:async()=>({user:{id:'a',email:'a@example.invalid'}}),changePassword:async()=>({token:'server-only-rotated-token'})},$context:Promise.resolve({internalAdapter:{deleteSession:async token=>{assert.equal(token,'server-only-rotated-token');removed++;}}})};
 const accountModule=loadModule('lib/actions/identity.actions.ts',{'next/headers':{headers:async()=>new Headers()},'../auth':{auth},'better-auth/api':{},'../account/store':{},'../account/identity-context':{},'../account/email/challenges':{},'../account/email/policy':{emailAddress:loadModule('lib/account/preferences.ts').preferenceSchema},'../account/email/delivery':{enqueueMail:async()=>true,processMailQueue:async()=>[]},'../account/email/templates':{mailTemplate:()=>({})},'../account/email/crypto':{},'../account/password':{},'../account/birth-date':{dateOfBirthSchema:loadModule('lib/account/preferences.ts').preferenceSchema},'../session':{},'../legal/validation':{},'../legal/store':{},'../account/signup':{}});return {...accountModule,removed:()=>removed};}
test('native password change revokes the rotated session without returning its token; web default stays compatible',async()=>{const native=identityActions();const result=await native.changeAccountPassword({currentPassword:'current',newPassword:'unique-passphrase'},true);assert.equal(result.ok,true);assert.equal(native.removed(),1);assert.ok(!JSON.stringify(result).includes('rotated-token'));const web=identityActions();assert.equal((await web.changeAccountPassword({currentPassword:'current',newPassword:'unique-passphrase'})).ok,true);assert.equal(web.removed(),0);});

test('native export omits source identifiers while retaining owned entitlement and trial fields',async()=>{
 const data={schemaVersion:3,account:{id:'a'},membership:{trialEndsAt:'2026-10-10T12:00:00Z',sources:[{provider:'apple',subscriptionId:'provider-only',currency:'USD',confirmed:true}]}};
 const accountModule=loadModule('lib/mobile/account.ts',{'next/headers':{},'../account/store':{},'../account/email/crypto':{},'../account/email/challenges':{},'../actions/identity.actions':{},'../actions/account.actions':{},'../actions/privacy.actions':{exportAccountData:async()=>success(data)},'./http':{MobileError}});
 const result=await accountModule.exportMobileAccount();assert.equal(result.membership.trialEndsAt,data.membership.trialEndsAt);assert.equal(result.membership.sources[0].provider,'apple');assert.equal(result.membership.sources[0].subscriptionId,undefined);assert.equal(data.membership.sources[0].subscriptionId,'provider-only');
});
