import test from 'node:test';
import assert from 'node:assert/strict';
import {loadModule} from './helpers.mjs';
import {events} from './gym-fixture.mjs';
const types=loadModule('lib/notifications/types.ts'),contract=loadModule('lib/mobile/inbox-contract.ts',{'../notifications/types':types});
function adapter(){let target={kind:'goal',id:'owned'},exists=true,ownerSeen,conflict=false;const stored={...target};void stored;const service=loadModule('lib/mobile/inbox.ts',{'./inbox-contract':contract,'./http':{MobileError:class extends Error{constructor(status,code,message){super(message);this.status=status;this.code=code;}}},'../actions/account.actions':{saveAccountSettingsResult:async input=>({ok:true,value:{revision:input.revision+1,notifications:input.value}})},'../events':events,'../notifications/store':{listInbox:async(owner,input)=>{ownerSeen=owner;return input;},inboxDetail:async(owner,id)=>{ownerSeen=owner;if(id==='foreign')throw Error('This message is no longer available');return {target};},setInboxState:async()=>{if(conflict)throw Error('This message changed or is no longer available');return {saved:true};},markAvailableRead:async()=>({saved:true,count:1}),reconcileInbox:async()=>{}},'../account/store':{accountSettings:async()=>({notifications:{email:false,marketing:false,trialReminder:true}}),accountSql:async()=>exists?[{data:{tracker:{goals:[{id:'owned'}]},journeys:[{id:'journey'}]},date:'2026-10-04'}]:[]}});return {service,get owner(){return ownerSeen;},set target(v){target=v;},set exists(v){exists=v;},set conflict(v){conflict=v;}};}
test('thin inbox adapter forces unread, trusts session owner and rejects client ownership/creation',async()=>{const h=adapter();assert.equal((await h.service.readMobileInbox('trusted',{})).filter,'unread');assert.equal(h.owner,'trusted');await assert.rejects(()=>h.service.readMobileInbox('trusted',{filter:'all',userId:'foreign'}));await assert.rejects(()=>h.service.writeMobileInbox('trusted',{type:'publish'}));assert.deepEqual(await h.service.writeMobileInbox('trusted',{type:'read-all'}),{saved:true,count:1});});
test('foreign/withdrawn message and stale writes expose actionable conflict without private content',async()=>{const h=adapter();await assert.rejects(()=>h.service.readMobileInboxDetail('trusted',{id:'foreign'}),error=>error.status===409&&error.code==='conflict');h.conflict=true;await assert.rejects(()=>h.service.writeMobileInbox('trusted',{type:'state',change:{id:'a',revision:1,read:true}}),error=>error.status===409);});
test('structured targets resolve from owned stored detail and current owned source, with no arbitrary URL',async()=>{const h=adapter();assert.equal((await h.service.readMobileInboxTarget('trusted',{id:'message'})).target.id,'owned');h.exists=false;await assert.rejects(()=>h.service.readMobileInboxTarget('trusted',{id:'message'}),error=>error.status===409);h.exists=true;h.target={kind:'workout',record:'plan',id:'plan',date:'2026-10-05'};await assert.rejects(()=>h.service.readMobileInboxTarget('trusted',{id:'message'}));await assert.rejects(()=>h.service.readMobileInboxTarget('trusted',{id:'message',target:{kind:'account',section:'security'}}));});

test('inbox preferences adapt canonical revisioned settings and preserve unexposed legacy flags',async()=>{const h=adapter(),data={eventReminders:true,goalReminders:false,weeklyReview:true,workoutCompletion:true,productUpdates:false,quietHours:true,quietFrom:'22:00',quietTo:'08:00'},result=await h.service.writeMobileInbox('trusted',{type:'settings',revision:3,data});assert.equal(result.settings.revision,4);assert.equal(result.settings.notifications.email,false);assert.equal(result.settings.notifications.marketing,false);assert.equal(result.settings.notifications.trialReminder,true);await assert.rejects(()=>h.service.writeMobileInbox('trusted',{type:'settings',revision:3,data:{...data,email:true}}));});
