"use client";
import { useAccountFormat } from "@/hooks/use-account-format";

import { ArrowDownLeft, ArrowUpRight, Wallet, ArrowRight, Plus } from "lucide-react";
import { Button } from "@/app/components/ui/button";
import { financeTrend, localDate, spendingCategories, summarizeFinance, type FinanceEntry, type MoneyType } from "@/lib/finance";

export default function FinanceDashboard({ entries, allEntries, month, onAdd, onHistory, onShowAll }: {
  entries: FinanceEntry[]; allEntries: FinanceEntry[]; month: string;
  onAdd: (type: MoneyType) => void; onHistory: () => void; onShowAll: () => void;
}) {
  const {formatAmount, formatFinanceDate}=useAccountFormat();
  const totals = summarizeFinance(entries);
  const categories = spendingCategories(entries);
  const trendEnd = month === "all" ? [...allEntries.map((row) => row.date.slice(0, 7))].sort().at(-1) || localDate().slice(0, 7) : month;
  const trend = financeTrend(allEntries, trendEnd);
  const max = Math.max(...trend.flatMap((row) => [row.revenue, row.spending]), 1);
  const recent = [...entries].sort((a, b) => b.date.localeCompare(a.date)).slice(0, 4);
  const stats = [
    { label: "Revenue", value: totals.revenue, Icon: ArrowDownLeft, color: "text-sky-300", background: "bg-sky-400/10", caption: "Money coming in" },
    { label: "Spending", value: totals.spending, Icon: ArrowUpRight, color: "text-orange-300", background: "bg-orange-400/10", caption: "Money going out" },
    { label: "Net balance", value: totals.balance, Icon: Wallet, color: totals.balance < 0 ? "text-orange-300" : "text-foreground", background: "bg-muted", caption: "Revenue minus spending" },
  ];
  return (
    <div className="space-y-5">
      {!entries.length && allEntries.length > 0 && <div className="flex flex-col gap-3 rounded-2xl border border-border bg-card px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-medium">A fresh start for this month</p><p className="mt-1 text-xs text-muted-foreground">Your earlier transactions are still in your history.</p></div><Button variant="ghost" className="h-11 justify-start text-sky-300" onClick={onShowAll}>See all transactions <ArrowRight size={15} /></Button></div>}
      <div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{stats.map(({ label, value, Icon, color, background, caption }) => <div key={label} className={`min-w-0 rounded-2xl border border-border bg-card p-4 sm:p-5 ${label === "Net balance" ? "order-first col-span-2 sm:order-last sm:col-span-1" : ""}`}><div className="flex items-center justify-between gap-2"><p className="text-sm text-muted-foreground">{label}</p><span className={`flex size-9 shrink-0 items-center justify-center rounded-xl ${background} ${color}`}><Icon size={18} /></span></div><p className={`mt-3 text-2xl font-semibold tracking-tight tabular-nums wrap-anywhere sm:text-3xl ${color}`}>{formatAmount(value)}</p><p className="mt-2 text-xs text-muted-foreground">{caption}</p></div>)}</div>
      {!allEntries.length && <div className="rounded-3xl border border-dashed border-border bg-card/50 p-6 text-center sm:p-9"><div className="mx-auto flex size-12 items-center justify-center rounded-2xl bg-orange-400/10 text-orange-300"><Wallet /></div><h2 className="mt-4 text-xl">A clearer picture starts here</h2><p className="mx-auto mt-2 max-w-sm text-sm leading-relaxed text-muted-foreground">Log your first expense or paycheck. Your dashboard will take care of the bigger picture.</p><div className="mt-5 flex flex-wrap justify-center gap-3"><Button className="h-11 bg-orange-400 text-orange-950 hover:bg-orange-300" onClick={() => onAdd("-")}><Plus size={16} /> Add spending</Button><Button variant="outline" className="h-11 text-sky-300" onClick={() => onAdd("+")}><Plus size={16} /> Add revenue</Button></div></div>}
      <div className="grid gap-5 xl:grid-cols-[1.4fr_1fr]">
        <section className="min-w-0 rounded-3xl border border-border bg-card p-5 sm:p-6" aria-labelledby="finance-flow-title">
          <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 id="finance-flow-title" className="text-base font-semibold">Cash flow</h2><p className="mt-1 text-xs text-muted-foreground">Six months ending {new Date(`${trendEnd}-01T00:00:00Z`).toLocaleDateString("en", { month: "long", year: "numeric", timeZone: "UTC" })}</p></div><div className="flex gap-3 text-xs text-muted-foreground"><span className="flex items-center gap-1.5"><span className="size-2 rounded-full bg-sky-400" /> Revenue</span><span className="flex items-center gap-1.5"><span className="size-2 rounded-full bg-orange-400" /> Spending</span></div></div>
          <div className="relative mt-6"><div aria-hidden className="pointer-events-none absolute inset-x-0 top-0 flex h-40 flex-col justify-between"><div className="border-t border-dashed border-border" /><div className="border-t border-dashed border-border" /><div className="border-t border-dashed border-border" /></div><div className="relative grid grid-cols-6 gap-2 sm:gap-5">{trend.map((row) => <div key={row.month} className="group min-w-0" tabIndex={0} aria-label={`${row.month}: revenue ${formatAmount(row.revenue)}, spending ${formatAmount(row.spending)}`}><div className="flex h-40 items-end justify-center gap-1.5"><div className="w-3 max-w-6 flex-1 rounded-t-md bg-sky-400 transition-all duration-300" style={{ height: `${row.revenue ? Math.max(row.revenue / max * 100, 2) : 0}%` }} /><div className="w-3 max-w-6 flex-1 rounded-t-md bg-orange-400 transition-all duration-300" style={{ height: `${row.spending ? Math.max(row.spending / max * 100, 2) : 0}%` }} /></div><p className="mt-3 text-center text-xs text-muted-foreground">{row.label}</p><div className="pointer-events-none absolute bottom-8 left-0 z-10 hidden rounded-xl border bg-popover p-3 text-xs shadow-xl group-hover:block group-focus:block"><p className="mb-1 font-medium">{row.month}</p><p className="text-sky-300">Revenue {formatAmount(row.revenue)}</p><p className="text-orange-300">Spending {formatAmount(row.spending)}</p></div></div>)}</div></div>
          {!trend.some((row) => row.revenue || row.spending) && <p className="mt-4 text-center text-xs text-muted-foreground">Your monthly activity will appear here.</p>}
        </section>
        <section className="min-w-0 rounded-3xl border border-border bg-card p-5 sm:p-6" aria-labelledby="finance-category-title"><h2 id="finance-category-title" className="text-base font-semibold">Where your money goes</h2><p className="mt-1 text-xs text-muted-foreground">Spending by category in this period</p><div className="mt-5 space-y-4">{categories.slice(0, 5).map((row) => <div key={row.category}><div className="flex items-center justify-between gap-3 text-sm"><span className="truncate">{row.category}</span><span className="shrink-0 text-xs tabular-nums text-muted-foreground">{formatAmount(row.amount)} <span className="ml-1">{totals.spending ? Math.round(row.amount / totals.spending * 100) : 0}%</span></span></div><div className="mt-2 h-1.5 rounded-full bg-muted"><div className="h-full rounded-full bg-orange-400" style={{ width: `${totals.spending ? row.amount / totals.spending * 100 : 0}%` }} /></div></div>)}{!categories.length && <p className="py-10 text-center text-sm text-muted-foreground">No spending in this period.</p>}</div></section>
      </div>
      <section className="rounded-3xl border border-border bg-card p-5 sm:p-6"><div className="mb-2 flex items-center justify-between"><h2 className="text-base font-semibold">Recent activity</h2><Button variant="ghost" onClick={onHistory} className="h-11 text-xs text-muted-foreground">View history <ArrowRight size={14} /></Button></div>{recent.map((row) => <div key={row.id} className="flex items-center gap-3 border-t border-border py-4"><span className={`flex size-10 shrink-0 items-center justify-center rounded-xl ${row.type === "+" ? "bg-sky-400/10 text-sky-300" : "bg-orange-400/10 text-orange-300"}`}>{row.type === "+" ? <ArrowDownLeft size={18} /> : <ArrowUpRight size={18} />}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{row.subcategory || row.category || "Transaction"}</p><p className="mt-1 text-xs text-muted-foreground">{formatFinanceDate(row.date)}</p></div><p className={`shrink-0 text-sm font-semibold tabular-nums ${row.type === "+" ? "text-sky-300" : "text-orange-300"}`}>{row.type === "+" ? "+" : "−"}{formatAmount(row.amount)}</p></div>)}{!recent.length && <p className="py-6 text-center text-sm text-muted-foreground">No transactions in this period.</p>}</section>
    </div>
  );
}
