"use client";
import { useMemo, useState } from "react";
import { CalendarPlus, Clock, Heart, Play, Save, SlidersHorizontal, Sparkles } from "lucide-react";
import { appendCardio, cardioAddons, cardioPresets, estimateMinutes, previousWeights, resolveCardio, resolveStrength, strengthPresets, substitute, type Addon, type CardioPreset, type StrengthPreset } from "@/lib/gym/presets";
import { equipmentFor, presetExercises } from "@/lib/gym/catalogue";
import { weightDisplay, weightStore } from "@/lib/gym/logic";
import { blueprintSchema } from "@/lib/gym/validation";
import type { Blueprint, GymData, Targets, Units, WorkoutExercise } from "@/lib/gym/types";
import { dateLabel } from "@/lib/gym/dates";
import { untimed } from "@/lib/planner-time";
import TimingFields from "../events/TimingFields";
import { Field, GymButton, GymDialog, GymSelect, NumberField } from "./GymUI";
import { GymReveal } from "./GymMotion";
import GymSafety from "./GymSafety";
import CatalogueIcon from "./CatalogueIcon";
import ExerciseIcon from "./ExerciseIcon";

type Props = {data: GymData; today: string; selected: string; units: Units; onSave: (data: Blueprint, copyId: string) => Promise<void>; onSchedule: (data: Blueprint, dates: string[]) => Promise<void>; onStart: (data: Blueprint) => Promise<void>; onBuild: (data: Blueprint) => void; onOpenPlan: (id: string) => void; onResume: (id: string) => void};
type Selection = StrengthPreset | CardioPreset | {id: string; name: string; personal: Blueprint};
const sections = ["Featured", "Full body", "Upper / Lower", "Push / Pull / Legs", "Muscle focus", "Cardio", "My presets", "Favorites", "Recent"];
function cardDraft(preset: Selection): Blueprint {
  return "personal" in preset ? preset.personal : "blocks" in preset ? resolveStrength(preset, "foundation") : resolveCardio(preset, preset.variants[0]);
}
export default function WorkoutPresets(props: Props) {
  const [group, setGroup] = useState("Featured"), [search, setSearch] = useState(""), [equipment, setEquipment] = useState(""), [time, setTime] = useState(""), [selection, setSelection] = useState<Selection | null>(null);
  const cards = useMemo(() => {
    const personal = props.data.templates.map(record => ({id: record.id, name: record.data.name, personal: record.data}));
    const recentIds = new Set(props.data.sessions.flatMap(session => session.data.originalPlan?.preset ? [session.data.originalPlan.preset.id] : []));
    const all: Selection[] = group === "My presets" ? personal : group === "Favorites" ? personal.filter(item => item.personal.favorite ?? item.personal.preset?.favorite) : [...strengthPresets, ...cardioPresets];
    return all.filter(preset => (group === "Featured" ? "featured" in preset && preset.featured : group === "Recent" ? recentIds.has(preset.id) : ["My presets", "Favorites"].includes(group) || group === "Cardio" ? group !== "Cardio" || "variants" in preset : "group" in preset && preset.group === group)
      && preset.name.toLowerCase().includes(search.toLowerCase())).map(preset => ({preset, draft: cardDraft(preset)}))
      .filter(({draft}) => (!equipment || draft.exercises.some(item => item.phase !== "preparation" && item.definition.equipment === equipment)) && (!time || draft.estimatedMinutes === null || draft.estimatedMinutes <= Number(time)));
  }, [props.data, group, search, equipment, time]);
  return <section className="space-y-5" aria-label="Workout presets">
    <div className="flex items-start gap-3"><Sparkles className="gym-blue mt-1 shrink-0" /><div><h2 className="text-2xl font-semibold">Find your next workout</h2><p className="mt-1 text-sm text-muted-foreground">Exercise selections · choose your own training targets</p><p className="mt-2 text-xs font-semibold uppercase tracking-wider text-[var(--gym-orange)]">Development preview · qualified coach review pending</p></div></div>
    <GymSafety />
    <div className="flex flex-wrap gap-2" role="group" aria-label="Preset collections">{sections.map(section => <GymButton key={section} tone={group === section ? "blue" : "neutral"} aria-pressed={group === section} onClick={() => setGroup(section)}>{section}</GymButton>)}</div>
    <div className="grid items-end gap-3 sm:grid-cols-2 lg:grid-cols-3"><Field label="Search workouts" placeholder="Chest, back, full body…" value={search} onChange={event => setSearch(event.target.value)} /><GymSelect label="Includes equipment" value={equipment} options={["", "Machine", "Dumbbells", "Barbell", "Cable", "Bodyweight", "Treadmill", "Stationary bike", "Rowing machine", "Elliptical"]} onChange={setEquipment} /><GymSelect label="Your estimated time (minutes)" value={time} options={["", "30", "45", "60", "90"]} onChange={setTime} /></div>
    <p role="status" className="text-sm text-muted-foreground">{cards.length} routines · weights and repetitions are entered by you</p>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{cards.map(({preset, draft}, index) => {
      const main = draft.exercises.filter(item => item.phase !== "preparation"), hardware = equipmentFor(main);
      const sets = main.filter(item => item.definition.tracking !== "cardio").reduce((sum, item) => sum + item.targets.sets, 0);
      return <GymReveal key={preset.id} delay={Math.min(index, 6) * .025}><article className="gym-tile flex h-full flex-col rounded-3xl border border-border bg-card/20 p-5">
        <div className="mb-4 flex min-h-28 items-center justify-center gap-2 rounded-2xl bg-background">{main.slice(0, 2).map(item => <ExerciseIcon key={item.id} icon={item.definition.icon} exerciseId={item.definition.id} size={104} />)}</div>
        <p className="text-xs font-semibold uppercase tracking-wider text-[var(--gym-blue)]">{"blocks" in preset ? preset.group : "personal" in preset ? "Personal copy" : "Cardio"}</p><h3 className="mt-2 text-lg font-semibold">{preset.name}</h3>
        <p className="mt-2 text-sm text-muted-foreground">{main.length} exercises{"personal" in preset && sets ? ` · ${sets} saved sets` : ""}</p><p className="mt-1 flex items-center gap-2 text-sm text-muted-foreground"><Clock size={15} />{draft.estimatedMinutes === null ? "Set your own targets" : `${draft.estimatedMinutes} min · editable`}</p>
        <p className="mt-2 text-xs text-muted-foreground">{"blocks" in preset ? "Exercise selection only · weights and reps start blank" : "Choose your own duration"}</p>
        <p className="mt-2 text-xs text-muted-foreground">{hardware.slice(0, 3).map(item => item.name).join(" · ")}{hardware.length > 3 ? ` +${hardware.length - 3}` : ""}</p>
        <p className="mb-4 mt-3 text-xs text-[var(--gym-orange)]">{draft.preset ? "Unreviewed programming preview" : "Your saved routine"}</p><GymButton className="mt-auto w-full" tone="blue" onClick={() => setSelection(preset)}>Review workout</GymButton>
      </article></GymReveal>;
    })}</div>
    {!cards.length && <p className="rounded-3xl border border-dashed p-8 text-center text-muted-foreground">{group === "Favorites" ? "Save a favorite personal copy from a preview to keep it here." : group === "Recent" ? "Presets you start will appear here. Your history starts with your real training." : group === "My presets" ? "Save a personal copy or build your own routine." : "No routines match these filters. Try a longer time or different equipment."}</p>}
    {selection && <PresetPreview key={selection.id} selection={selection} {...props} onClose={() => setSelection(null)} />}
  </section>;
}
function PresetPreview({selection, onClose, ...props}: Props & {selection: Selection; onClose: () => void}) {
  const strength = "blocks" in selection ? selection : null, cardio = "variants" in selection ? selection : null;
  const [draft, setDraft] = useState(() => structuredClone(cardDraft(selection))),
    [addon, setAddon] = useState<Addon>("none"), [addonMinutes, setAddonMinutes] = useState(10), [duration, setDuration] = useState(cardio?.variants[0] || 20), [jog, setJog] = useState(false),
    [schedule, setSchedule] = useState(false), [date, setDate] = useState(props.selected), [busy, setBusy] = useState(false), [error, setError] = useState(""), [message, setMessage] = useState(""),
    [favorite, setFavorite] = useState(Boolean(cardDraft(selection).favorite ?? cardDraft(selection).preset?.favorite)), [saved, setSaved] = useState(false), [copyId] = useState(() => crypto.randomUUID()), [experienced, setExperienced] = useState(false);
  const patch = (id: string, change: Partial<Targets>) => setDraft(current => ({...current, exercises: current.exercises.map(item => item.id === id ? {...item, targets: {...item.targets, ...change}, ...(change.seconds !== undefined && item.definition.tracking === "cardio" ? {notes: `Custom planned duration: ${change.seconds === null ? "unknown" : change.seconds / 60} minutes total. Include a gradual easy start and finish. Ask a trainer to adapt the segments; no duration or distance is logged automatically.`} : {})} : item)}));
  const run = async (operation: (data: Blueprint) => Promise<void>, success: string) => {
    setBusy(true); setError("");
    try {const data = blueprintSchema.parse({...draft, favorite, estimatedMinutes: draft.estimatedMinutes ?? estimateMinutes(draft.exercises), ...(draft.preset ? {preset: {...draft.preset, favorite}} : {})}); await operation(data); setMessage(success);}
    catch (reason) {setError(reason instanceof Error ? reason.message : "Save failed — retry");}
    finally {setBusy(false);}
  };
  const todayPlans = props.data.plans.filter(plan => plan.date === props.today), active = props.data.sessions.filter(session => session.data.status === "active");
  const minutes = draft.estimatedMinutes ?? estimateMinutes(draft.exercises), hardware = equipmentFor(draft.exercises);
  return <GymDialog open full title={selection.name} description="Review this unreviewed preview, choose personal targets, then save, schedule or start. Planned values never become actual results automatically." onClose={() => {if (!busy) onClose();}}>
    <GymSafety compact />
    {cardio && <div className="space-y-3"><div className="flex flex-wrap gap-2" role="group" aria-label="Cardio duration">{cardio.variants.map(value => <GymButton key={value} tone={duration === value ? "blue" : "neutral"} onClick={() => {setDuration(value); setDraft(resolveCardio(cardio, value, jog)); setSaved(false);}}>{value} min total</GymButton>)}</div><NumberField label="Or a shorter manageable duration (minutes)" min={1} max={cardio.variants.at(-1)} value={duration} onChange={value => {if (value && (cardio.variants.includes(value) || value < cardio.variants[0])) {setDuration(value); setDraft(resolveCardio(cardio, value, jog)); setSaved(false);}}} />
      <p className="text-sm text-muted-foreground">Opening and closing easy segments are included. Moderate effort: able to talk but not sing. Duration is independent from your lifting profile. No distance, calories or heart-rate zone is inferred.</p>
      {cardio.id === "cardio-walk-run" && <label className="flex min-h-11 items-center gap-3"><input type="checkbox" className="size-5 accent-[var(--gym-blue)]" checked={jog} onChange={event => {setJog(event.target.checked); setDraft(resolveCardio(cardio, duration, event.target.checked));}} />Choose comfortable jog segments; otherwise walking only.</label>}
      {cardio.experienced && <label className="flex min-h-11 items-center gap-3 text-sm"><input type="checkbox" className="size-5 accent-[var(--gym-blue)]" checked={experienced} onChange={event => setExperienced(event.target.checked)} />I deliberately chose controlled intervals and have discussed appropriate effort with a trainer. Easy recovery segments remain included.</label>}
      {cardio.id === "cardio-row" && <p className="text-sm text-[var(--gym-orange)]">Get a trainer’s technique introduction before rowing if you are unfamiliar with it.</p>}
    </div>}
    <div className="gym-blue flex flex-wrap items-center justify-between gap-3 rounded-2xl border p-4"><div><p className="font-semibold">{minutes === null ? "Your exercises, your targets" : `${minutes} minutes · estimated`}</p><p className="text-xs text-muted-foreground">Enter your own weights and repetitions. One blank row is provided to start logging.</p></div><p className="text-sm">{draft.exercises.filter(item => item.phase !== "preparation").length} exercises · {draft.exercises.filter(item => item.phase === "strength").reduce((sum, item) => sum + item.targets.sets, 0)} working sets</p></div>
    <Field label="Workout name" maxLength={120} value={draft.name} onChange={event => {setDraft({...draft, name: event.target.value}); setSaved(false);}} />
    <div className="space-y-3">{draft.exercises.map((item, index) => <PresetExercise key={item.id} item={item} index={index} units={props.units} data={props.data} today={props.today} onPatch={change => {patch(item.id, change); setSaved(false);}} onSubstitute={slug => {setDraft(current => ({...current, exercises: current.exercises.map(exercise => exercise.id === item.id ? substitute(exercise, slug) : exercise)})); setSaved(false);}} />)}</div>
    {strength && <section className="space-y-3 rounded-2xl border border-border bg-card/20 p-4"><h3 className="font-semibold">Cardio after training · optional</h3><div className="flex flex-wrap gap-2" role="group" aria-label="Cardio after training">{[{id: "none", name: "None"}, ...cardioAddons].map(option => <GymButton key={option.id} tone={addon === option.id ? "blue" : "neutral"} onClick={() => {setAddon(option.id as Addon); setDraft(appendCardio(draft, option.id as Addon, addonMinutes)); setSaved(false);}}>{option.name}</GymButton>)}</div>{addon !== "none" && <div className="flex gap-2">{[10,15,20].map(value => <GymButton key={value} tone={addonMinutes === value ? "blue" : "neutral"} onClick={() => {setAddonMinutes(value); setDraft(appendCardio(draft, addon, value)); setSaved(false);}}>{value} min total</GymButton>)}</div>}<p className="text-xs text-muted-foreground">One phase of the same workout. Includes 2 easy minutes at each end. None or a short easy option is reasonable after demanding leg training; no recovery or fat-loss benefit is promised.</p></section>}
    <details className="rounded-2xl border border-border p-4"><summary className="cursor-pointer font-semibold">Equipment for this resolved workout</summary><div className="mt-3 flex flex-wrap gap-2">{hardware.map(item => <div key={item.id} className="flex max-w-full items-center gap-2 rounded-xl border p-2"><CatalogueIcon id={item.id} size={56} /><span className="text-xs">{item.name}</span></div>)}</div><p className="mt-2 text-xs text-muted-foreground">Illustrated setup requirements. A trainer should confirm your actual apparatus. Different machines and variants do not share interchangeable loads.</p></details>
    {(todayPlans.length > 0 || active.length > 0) && <section className="space-y-2 rounded-2xl border border-border p-4"><h3 className="font-semibold">Your existing training</h3>{todayPlans.map(plan => <GymButton key={plan.id} onClick={() => {props.onOpenPlan(plan.id); onClose();}}>Open today’s plan: {plan.data.name}</GymButton>)}{active.map(session => <GymButton key={session.id} tone="orange" onClick={() => {props.onResume(session.id); onClose();}}>Resume {session.data.name}</GymButton>)}<p className="text-xs text-muted-foreground">Starting separately creates another workout. Your existing plan or active log stays intact.</p></section>}
    <label className="flex min-h-11 items-center gap-3 text-sm"><input type="checkbox" className="size-5 accent-[var(--gym-blue)]" checked={favorite} onChange={event => {setFavorite(event.target.checked); setSaved(false);}} /><Heart size={16} />Save this personal copy in Favorites</label>
    {schedule && <div className="space-y-3 rounded-2xl border p-4"><Field label="Training date" type="date" value={date} onChange={event => setDate(event.target.value)} /><TimingFields disabled={busy} value={draft.timing || untimed()} onChange={timing => setDraft({...draft, timing})} /><GymButton tone="blue" disabled={busy || !date || cardio?.experienced && !experienced} onClick={() => run(async data => {await props.onSchedule(data, [date]); onClose();}, "Workout scheduled")}><CalendarPlus />Confirm date</GymButton></div>}
    {error && <p role="alert" className="gym-error">{error}</p>}{message && <p role="status" className="text-sm text-muted-foreground">{message}</p>}
    <div className="sticky bottom-0 -mx-5 flex flex-wrap gap-2 border-t border-border bg-background px-5 py-3">
      <GymButton disabled={busy || saved || cardio?.experienced && !experienced} tone="blue" onClick={() => run(async data => {await props.onSave(data, copyId); setSaved(true);}, "Personal copy saved to your account")}><Save />{saved ? "Copy saved" : "Save personal copy"}</GymButton>
      <GymButton disabled={busy || cardio?.experienced && !experienced} onClick={() => setSchedule(!schedule)}><CalendarPlus />Add to date</GymButton>
      <GymButton disabled={busy || cardio?.experienced && !experienced} tone="orange" onClick={() => run(async data => {await props.onStart(data); onClose();}, "Workout started")}><Play />{busy ? "Saving…" : todayPlans.length || active.length ? "Start separate workout" : "Start now"}</GymButton>
      <GymButton disabled={busy} onClick={() => {props.onBuild({...draft, estimatedMinutes: minutes}); onClose();}}><SlidersHorizontal />Customize in builder</GymButton>
    </div>
  </GymDialog>;
}
function PresetExercise({item, index, units, data, today, onPatch, onSubstitute}: {item: WorkoutExercise; index: number; units: Units; data: GymData; today: string; onPatch: (change: Partial<Targets>) => void; onSubstitute: (slug: string) => void}) {
  const loaded = ["weight-reps", "assistance-reps"].includes(item.definition.tracking), previous = loaded ? previousWeights(item, data.sessions, today) : null;
  const candidates = presetExercises.filter(exercise => item.definition.alternatives.includes(exercise.id));
  return <article className="rounded-2xl border border-border bg-card/20 p-4">
    <header className="flex items-center gap-3"><ExerciseIcon icon={item.definition.icon} exerciseId={item.definition.id} size={80} /><div><p className="text-xs font-semibold uppercase tracking-wider text-[var(--gym-blue)]">{item.phase === "preparation" ? "Preparation" : item.phase === "cardio" ? "Cardio" : `Exercise ${index + 1}`}</p><h3 className="font-semibold">{item.definition.name}</h3><p className="mt-1 text-xs text-muted-foreground">{item.definition.loadConvention === "none" ? item.definition.equipment : item.definition.loadConvention}{item.definition.perSide ? " · each side" : ""}</p></div></header>
    <p className="my-3 text-sm"><strong>Planned:</strong> {item.definition.tracking === "cardio" ? (item.targets.seconds === null ? "Duration not set" : `${item.targets.seconds / 60} minutes total`) : `${item.targets.sets} sets × ${item.targets.repRange ? item.targets.repRange.join("–") : (item.definition.tracking === "duration" ? item.targets.seconds : item.targets.reps) ?? "not set"} ${item.definition.tracking === "duration" ? "seconds per hold" : "reps"}`}{item.definition.perSide ? " on each side" : ""}{item.targets.restSeconds ? ` · rest ${item.targets.restSeconds}s` : ""}</p>
    <p className="whitespace-pre-line text-xs text-muted-foreground">{item.notes}</p>
    {loaded && <div className="mt-3 space-y-3"><p className="text-xs text-muted-foreground">Choose starting weight with a qualified trainer. The app does not recommend weights or repetitions. Zero is an explicit value; blank is unknown.{item.definition.loadConvention === "added plates" && " Log added plates only; unknown sled/lever mass is excluded."}{item.definition.loadConvention === "total external load" && " Include the actual configured bar in total external load."}</p><NumberField label={`Target ${item.definition.tracking === "assistance-reps" ? "assistance" : "load"} (${units.weight}, ${item.definition.loadConvention})`} value={item.targets.loadKg == null ? null : weightDisplay(item.targets.loadKg, units)} onChange={value => onPatch({loadKg: value === null ? null : weightStore(value, units), perSetLoadsKg: undefined})} />
      {["Machine", "Cable"].includes(item.definition.equipment) && <Field label="Apparatus identity (for matching previous loads)" placeholder="e.g. gym location / machine name" value={item.targets.apparatus || ""} maxLength={120} onChange={event => onPatch({apparatus: event.target.value || null})} />}
      {previous && <div className="space-y-2 rounded-xl border p-3"><p className="text-xs"><strong>Previous · {dateLabel(previous.date)}:</strong> {previous.loads.map(load => load == null ? "Unknown" : `${weightDisplay(load, units)} ${units.weight}`).join(" / ")}</p><p className="text-xs text-muted-foreground">{previous.reason}</p><GymButton disabled={!previous.compatible} onClick={() => onPatch({perSetLoadsKg: previous.loads, loadKg: previous.loads[0] ?? null})}>Use my previous weights</GymButton></div>}
    </div>}
    <details open className="mt-3"><summary className="cursor-pointer text-sm font-medium">Adjust targets{candidates.length ? " / substitution candidates" : ""}</summary><div className="mt-3 grid gap-3 sm:grid-cols-2">
      {item.definition.tracking !== "cardio" && <><NumberField label="Working sets" min={1} max={30} step={1} value={item.targets.sets} onChange={value => {if (value && Number.isInteger(value)) onPatch({sets: value, perSetLoadsKg: item.targets.perSetLoadsKg?.slice(0, value)});}} /><NumberField label="Rest (seconds)" min={0} max={3600} value={item.targets.restSeconds} onChange={restSeconds => onPatch({restSeconds})} /></>}
      {!["duration", "cardio"].includes(item.definition.tracking) ? <><NumberField label={item.definition.perSide ? "Target repetitions per side" : "Target repetitions"} min={1} step={1} value={item.targets.reps} onChange={reps => onPatch({reps, repRange: undefined})} /><NumberField label="Estimated repetitions in reserve (blank = not sure)" min={0} max={10} value={item.targets.rir ?? null} onChange={rir => onPatch({rir})} /></> : <NumberField label={item.definition.tracking === "cardio" ? "Planned minutes" : "Seconds per hold"} min={1} value={item.targets.seconds == null ? null : item.targets.seconds / (item.definition.tracking === "cardio" ? 60 : 1)} onChange={value => onPatch({seconds: value === null ? null : value * (item.definition.tracking === "cardio" ? 60 : 1)})} />}
      {loaded && Array.from({length: item.targets.sets}, (_, setIndex) => {const load = item.targets.perSetLoadsKg && setIndex < item.targets.perSetLoadsKg.length ? item.targets.perSetLoadsKg[setIndex] : item.targets.loadKg; return <NumberField key={setIndex} label={`Planned set ${setIndex + 1} load (${units.weight})`} value={load == null ? null : weightDisplay(load, units)} onChange={value => {const loads = Array.from({length: item.targets.sets}, (_, i) => item.targets.perSetLoadsKg && i < item.targets.perSetLoadsKg.length ? item.targets.perSetLoadsKg[i] : item.targets.loadKg); loads[setIndex] = value === null ? null : weightStore(value, units); onPatch({perSetLoadsKg: loads});}} />;})}
    </div>
    {candidates.length > 0 && <div className="mt-3 space-y-2"><p className="text-xs text-muted-foreground">Unreviewed compatible movement candidates — a trainer must check suitability. Substitution clears numerical loads and apparatus identity.</p><div className="flex flex-wrap gap-2">{candidates.map(candidate => <GymButton key={candidate.id} onClick={() => onSubstitute(candidate.catalogueId!.slice("exercise:".length))}>{candidate.name}</GymButton>)}</div></div>}</details>
  </article>;
}
