"use client";
import { useAccountPreferences } from "./AccountPreferencesProvider";
import { useState, useEffect } from "react";
import { GymButton, GymSelect } from "@/app/(main)/account/gym/GymUI";
import { membershipStatus, startMembershipTrial, createMembershipCheckout, openMembershipPortal, expireMembershipCheckout, refreshMembership } from "@/lib/actions/billing.actions";
import { annualPrices, financeCurrencies, type BillingCurrency } from "@/lib/account/config";
type Status=Extract<Awaited<ReturnType<typeof membershipStatus>>,{ok:true}>["value"];
export default function MembershipSettings({initial,trialDays,stripeAvailable}:{initial:Status;trialDays:number;stripeAvailable:boolean}){
 const {settings}=useAccountPreferences();
 const date=(value:string)=>new Intl.DateTimeFormat(settings.preferences.numberLocale,{dateStyle:"medium",timeStyle:"short",timeZone:settings.preferences.timezone,hour12:settings.preferences.timeFormat==="12"}).format(new Date(value));
 const [status,setStatus]=useState(initial),[currency,setCurrency]=useState<BillingCurrency>("PLN"),[accept,setAccept]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const paidActive=!!status.paidThrough&&Date.parse(status.paidThrough)>Date.now();
 useEffect(()=>{if(!stripeAvailable||new URLSearchParams(window.location.search).get('billing')!=='confirming')return;let disposed=false,attempts=0;setMessage('Payment is awaiting provider confirmation. Return URLs do not grant access.');const poll=async()=>{const result=await refreshMembership();if(disposed)return;if(result.ok){const current=await membershipStatus();if(!disposed&&current.ok){setStatus(current.value);if(current.value.access.state.startsWith('paid')){setMessage('Payment confirmed. Annual access is active.');return;}}}if(++attempts<8)timer=setTimeout(poll,5000);else setMessage('Confirmation is pending. You can retry here; no duplicate purchase is needed.');};let timer:ReturnType<typeof setTimeout>=setTimeout(poll,1000);return()=>{disposed=true;clearTimeout(timer);};},[stripeAvailable]);
 async function reload(){const result=await membershipStatus();if(result.ok)setStatus(result.value);else setError(result.error);}
 async function act(run:()=>Promise<{ok:true;value:unknown}|{ok:false;error:string}>){if(busy)return;setBusy(true);setError("");try{const result=await run();if(!result.ok)throw new Error(result.error);if(result.value&&typeof result.value==="object"&&"url"in result.value){window.location.assign(String(result.value.url));return;}setMessage("Membership updated.");await reload();}catch(e){setError(e instanceof Error?e.message:"Membership request failed");}finally{setBusy(false);}}
 return <div className="space-y-5"><div className="rounded-2xl border p-4 space-y-2"><p className="font-semibold capitalize">{status.access.state.replaceAll("-"," ")}</p>{status.access.end&&<p className="text-sm">Access until {date(status.access.end)}</p>}{status.trialEnd&&<p className="text-sm">Trial ends {date(status.trialEnd)}</p>}{status.paidThrough&&<p className="text-sm">Paid access through {date(status.paidThrough)} · {status.renewalOff?"Renewal off":"Annual renewal on"} · {status.billingCurrency}</p>}{status.access.state==="launch-transition"&&<p className="text-sm text-muted-foreground">Membership enforcement is awaiting the configured launch cutover. Existing records and access are preserved during migration.</p>}{status.access.readOnly&&<p className="text-sm">Your saved records remain readable. Settings, security, support, billing, export and deletion remain available.</p>}{status.access.operatorReview&&<p role="status" className="text-sm">A billing adjustment requires operator review. Contact support.</p>}{status.syncError&&<p className="text-sm">{status.syncError}</p>}</div>
 {!status.trialStart&&!status.paidThrough&&<><p className="text-sm">One {trialDays}-day trial per account. No card needed. It starts only when you choose the action below.</p><GymButton tone="blue" disabled={busy} onClick={()=>act(startMembershipTrial)}>Start {trialDays}-day trial</GymButton></>}
 <section className="space-y-4 border-t pt-5"><h3 className="font-semibold">One annual membership</h3><GymSelect label="Billing currency — independent of Finance" value={currency} options={financeCurrencies} onChange={value=>{setCurrency(value as BillingCurrency);setAccept(false);}} disabled={busy||paidActive}/><p className="text-2xl font-semibold text-primary">{new Intl.NumberFormat(settings.preferences.numberLocale,{style:"currency",currency}).format(annualPrices[currency]/100)} / year</p><p className="text-sm text-muted-foreground">Full yearly charge. Displayed price includes configured applicable tax. Changing Finance currency never changes your subscription.</p><label className="flex items-start gap-3 text-sm"><input type="checkbox" className="mt-1 size-5 accent-primary" checked={accept} onChange={e=>setAccept(e.target.checked)}/><span>I understand this charges the annual price now and begins a paid annual period after payment. No second trial or deferred charge.</span></label><div className="flex flex-wrap gap-3"><GymButton tone="orange" disabled={busy||!accept||!stripeAvailable||paidActive} onClick={()=>act(()=>createMembershipCheckout({currency,acceptImmediateCharge:true}))}>Purchase annual membership</GymButton>{status.hasCustomer&&<GymButton tone="blue" disabled={busy} onClick={()=>act(openMembershipPortal)}>Manage payments, receipts & cancellation</GymButton>}{status.checkoutPending&&<GymButton disabled={busy} onClick={()=>act(expireMembershipCheckout)}>Close pending checkout</GymButton>}<GymButton disabled={busy||!stripeAvailable} onClick={()=>act(refreshMembership)}>Confirm membership status</GymButton></div>{!stripeAvailable&&<p role="status" className="text-sm text-muted-foreground">Checkout is unavailable until Stripe is configured. No payment has been requested.</p>}<p className="text-sm text-muted-foreground">Cancellation turns renewal off and preserves paid access until its end date. Use the secure billing portal to manage payment methods and invoices.</p></section>{busy&&<p role="status">Confirming membership…</p>}{message&&<p role="status">{message}</p>}{error&&<p role="alert" className="gym-error text-sm">{error}</p>}</div>;
}
