"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { PasswordInput } from "@/app/components/ui/password-input";
import { GymButton } from "@/app/(main)/account/gym/GymUI";
import { changeAccountPassword, accountSessions, revokeAccountSession, revokeOtherAccountSessions } from "@/lib/actions/identity.actions";
import { authClient } from "@/lib/auth-client";
import EmailProofForm from "./EmailProofForm";
type Sessions=Extract<Awaited<ReturnType<typeof accountSessions>>,{ok:true}>["value"];
export default function SecuritySettings({onEmailVerified}:{onEmailVerified?:(email:string)=>void}){
 const router=useRouter();
 const [current,setCurrent]=useState(""),[password,setPassword]=useState(""),[confirmation,setConfirmation]=useState(""),[message,setMessage]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[sessions,setSessions]=useState<Sessions|null>(null);
 async function load(){const result=await accountSessions();if(result.ok)setSessions(result.value);else setError(result.error);}
 return <div className="space-y-8"><section><h3 className="font-semibold">Change password</h3><p className="mt-2 text-sm text-muted-foreground">Use 15–128 characters. Long passphrases work well. We check predictable and known compromised passwords.</p><form className="mt-4 grid gap-4" onSubmit={async e=>{e.preventDefault();if(busy)return;setError("");if(password!==confirmation){setError("Passwords do not match");return;}setBusy(true);const result=await changeAccountPassword({currentPassword:current,newPassword:password});if(result.ok){setMessage(result.value.message);setCurrent("");setPassword("");setConfirmation("");void load();}else setError(result.error);setBusy(false);}}>{[["Current password",current,setCurrent],["New password",password,setPassword],["Confirm new password",confirmation,setConfirmation]].map(([label,value,set],i)=><label key={String(label)} className="grid gap-2 text-sm font-medium">{String(label)}<PasswordInput required autoComplete={i===0?"current-password":"new-password"} minLength={i?15:1} maxLength={128} value={String(value)} onChange={e=>(set as (value:string)=>void)(e.target.value)}/></label>)}<GymButton type="submit" tone="blue" disabled={busy}>{busy?"Saving…":"Change password & sign out other devices"}</GymButton></form></section>
 <section className="space-y-4 border-t pt-6"><h3 className="font-semibold">Change login email</h3><p className="text-sm text-muted-foreground">Your current email stays active until the new mailbox is verified. Account history and billing ownership remain on the same user ID.</p><EmailProofForm purpose="email-change" onVerified={onEmailVerified}/></section>
 <section className="space-y-4 border-t pt-6"><h3 className="font-semibold">Active devices</h3><div className="flex flex-wrap gap-3"><GymButton onClick={load}>Load active sessions</GymButton><GymButton disabled={busy} onClick={async()=>{setBusy(true);const result=await revokeOtherAccountSessions();if(result.ok){setMessage(result.value.message);await load();}else setError(result.error);setBusy(false);}}>Sign out other devices</GymButton></div>{sessions?.map(session=><article key={session.id} className="rounded-2xl border p-4 space-y-2"><p className="text-sm wrap-anywhere">{session.device}{session.current?" · Current device":""}</p><p className="text-xs text-muted-foreground">IP: {session.ip} · Last seen {new Date(session.lastSeen).toLocaleString()} · Location is not inferred.</p>{!session.current&&<GymButton onClick={async()=>{const result=await revokeAccountSession(session.id);if(result.ok)await load();else setError(result.error);}}>Sign out this device</GymButton>}</article>)}{sessions?.length===0&&<p>No active sessions found.</p>}<GymButton onClick={async()=>{await authClient.signOut();router.replace("/auth/login");}}>Sign out current device</GymButton></section>
 {message&&<p role="status" className="text-sm">{message}</p>}{error&&<p role="alert" className="gym-error text-sm">{error}</p>}</div>;
}
