"use client";
import { useState } from "react";
import Link from "next/link";
import { Field,GymButton } from "@/app/(main)/account/gym/GymUI";
import { PasswordInput,PasswordInputStrengthChecker } from "@/app/components/ui/password-input";
import EmailProofForm from "@/app/components/shared/account/EmailProofForm";
import { completeSignup } from "@/lib/actions/identity.actions";
export default function RegistrationForm(){
 const [verified,setVerified]=useState(false),[name,setName]=useState(""),[password,setPassword]=useState(""),[confirm,setConfirm]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 return <section className="gym-scope account-settings-panel space-y-5"><h1 className="text-2xl font-semibold">Create your B1-Way account</h1><p className="text-sm text-muted-foreground">First verify your mailbox. Then choose your own password. Your trial starts only when you explicitly start it in Account & Settings.</p>{!verified?<EmailProofForm purpose="signup" onVerified={()=>setVerified(true)}/>:<form className="space-y-4" onSubmit={async e=>{e.preventDefault();if(busy)return;setError("");if(password!==confirm){setError("Passwords do not match");return;}setBusy(true);const result=await completeSignup({name,password});if(result.ok)window.location.assign(result.value.redirect);else setError(result.error);setBusy(false);}}><p className="text-sm text-primary">Email verified</p><Field label="Display name" required maxLength={80} autoComplete="name" value={name} onChange={e=>setName(e.target.value)}/><label className="grid gap-2 text-sm font-medium">Password<PasswordInput required minLength={15} maxLength={128} autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)}><PasswordInputStrengthChecker/></PasswordInput></label><label className="grid gap-2 text-sm font-medium">Confirm password<PasswordInput required minLength={15} maxLength={128} autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)}/></label><p className="text-xs text-muted-foreground">15–128 characters. Long passphrases are welcome; common and compromised passwords are rejected.</p><GymButton tone="blue" type="submit" disabled={busy}>{busy?"Creating account…":"Create account"}</GymButton></form>}{error&&<p role="alert" className="gym-error text-sm">{error}</p>}<p className="text-sm"><Link className="underline" href="/auth/login">Sign in</Link> · <Link className="underline" href="/auth/forgot-password">Recover existing account</Link></p></section>;
}
