"use client";
import Link from "next/link";
import {Archive,Bell,Calendar,Check,Compass,Dumbbell,MailOpen,Target} from "lucide-react";
import {Button} from "@/app/components/ui/button";
import type {InboxMessage,InboxPage} from "@/lib/notifications/types";
const iconFor={event_reminder:Calendar,workout_completed:Dumbbell,goal_milestone:Target,journey_milestone:Compass,goal_reminder:Bell,weekly_review:Check,product_update:MailOpen};
export function InboxSkeleton(){return <div role="status" aria-label="Loading notifications" aria-busy="true" className="space-y-4 p-4">{[0,1,2].map(key=><div key={key} aria-hidden="true" className="flex gap-3"><span className="size-10 shrink-0 rounded-xl bg-muted motion-safe:animate-pulse"/><div className="flex-1 space-y-2"><span className="block h-4 w-2/3 rounded bg-muted motion-safe:animate-pulse"/><span className="block h-3 rounded bg-muted motion-safe:animate-pulse"/><span className="block h-3 w-1/3 rounded bg-muted motion-safe:animate-pulse"/></div></div>)}</div>;}
export default function InboxList({page,busy,onChange}:{page:InboxPage;busy:boolean;onChange:(message:InboxMessage,state:{read?:boolean;archived?:boolean})=>void}){
 const messages=page.messages.filter(message=>!message.readAt&&!message.archivedAt);
 if(!messages.length)return <div className="px-5 py-10 text-center"><Check className="mx-auto mb-3 text-primary-plus" aria-hidden="true"/><p className="font-medium">You’re all caught up</p><p className="mt-2 text-sm text-muted-foreground">New reminders and app messages will appear here.</p></div>;
 return <ul className="divide-y divide-border">{messages.map(message=>{const Icon=iconFor[message.category];return <li key={message.id} className="p-3 sm:p-4"><article className="flex gap-3"><div aria-hidden="true" className="mt-1 flex size-9 shrink-0 items-center justify-center rounded-xl border border-primary-plus/30 bg-primary-plus/10 text-primary-plus"><Icon size={18}/></div><div className="min-w-0 flex-1"><Link prefetch={false} href={`/account/notifications?message=${encodeURIComponent(message.id)}`} aria-disabled={busy} className="block rounded-lg text-left outline-none focus-visible:ring-2 focus-visible:ring-primary-plus" onClick={event=>{if(busy)event.preventDefault();}}><div className="flex items-start gap-2"><h3 className="min-w-0 flex-1 break-words text-sm font-semibold leading-6">{message.title}</h3><span className="mt-1 shrink-0 rounded-md bg-primary-plus/10 px-1.5 py-0.5 text-xs text-primary-plus">Unread</span></div><p className="mt-1 line-clamp-2 break-words text-sm leading-6 text-muted-foreground">{message.body}</p><time dateTime={message.availableAt} className="mt-2 block text-xs text-muted-foreground">{new Intl.DateTimeFormat(page.locale,{timeZone:page.timezone,month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(message.availableAt))}</time></Link><div className="mt-2 flex flex-wrap gap-1"><Button type="button" variant="ghost" disabled={busy} className="min-h-11 h-auto rounded-xl px-2 text-xs" aria-label={`Mark ${message.title} as read`} onClick={()=>onChange(message,{read:true})}><Check size={14}/>Mark read</Button><Button type="button" variant="ghost" disabled={busy} className="min-h-11 h-auto rounded-xl px-2 text-xs" aria-label={`Archive ${message.title}`} onClick={()=>onChange(message,{archived:true})}><Archive size={14}/>Archive</Button></div></div></article></li>;})}</ul>;
}